QT += network

HEADERS += \
# Models
    $${PWD}/OAIActivity.h \
    $${PWD}/OAIActivityNotification.h \
    $${PWD}/OAIActivityTopic.h \
    $${PWD}/OAIActivity_template.h \
    $${PWD}/OAIActivity_times.h \
    $${PWD}/OAIAggregationOption.h \
    $${PWD}/OAIAppRole.h \
    $${PWD}/OAIAppRoleAssignment.h \
    $${PWD}/OAIApplication.h \
    $${PWD}/OAIAudio.h \
    $${PWD}/OAIBucketAggregationRange.h \
    $${PWD}/OAIBucketDefinition.h \
    $${PWD}/OAIClass_Member_Reference.h \
    $${PWD}/OAIClass_Reference.h \
    $${PWD}/OAIClass_Teacher_Reference.h \
    $${PWD}/OAICollection_of_activities.h \
    $${PWD}/OAICollection_of_appRoleAssignments.h \
    $${PWD}/OAICollection_of_applications.h \
    $${PWD}/OAICollection_of_class.h \
    $${PWD}/OAICollection_of_driveItems.h \
    $${PWD}/OAICollection_of_driveItems_1.h \
    $${PWD}/OAICollection_of_drives.h \
    $${PWD}/OAICollection_of_drives_1.h \
    $${PWD}/OAICollection_of_educationClass.h \
    $${PWD}/OAICollection_of_educationUser.h \
    $${PWD}/OAICollection_of_group.h \
    $${PWD}/OAICollection_of_invitations.h \
    $${PWD}/OAICollection_of_permissions.h \
    $${PWD}/OAICollection_of_permissions_with_allowed_values.h \
    $${PWD}/OAICollection_of_schools.h \
    $${PWD}/OAICollection_of_tags.h \
    $${PWD}/OAICollection_of_user.h \
    $${PWD}/OAICollection_of_users.h \
    $${PWD}/OAIDeleted.h \
    $${PWD}/OAIDrive.h \
    $${PWD}/OAIDriveItem.h \
    $${PWD}/OAIDriveItemCreateLink.h \
    $${PWD}/OAIDriveItemInvite.h \
    $${PWD}/OAIDriveRecipient.h \
    $${PWD}/OAIDriveUpdate.h \
    $${PWD}/OAIEducationClass.h \
    $${PWD}/OAIEducationSchool.h \
    $${PWD}/OAIEducationUser.h \
    $${PWD}/OAIEducationUser_Reference.h \
    $${PWD}/OAIEmailAddress.h \
    $${PWD}/OAIExportPersonalData_request.h \
    $${PWD}/OAIFileSystemInfo.h \
    $${PWD}/OAIFolder.h \
    $${PWD}/OAIFolderView.h \
    $${PWD}/OAIGeoCoordinates.h \
    $${PWD}/OAIGeohashDefinition.h \
    $${PWD}/OAIGroup.h \
    $${PWD}/OAIGuestLinkError.h \
    $${PWD}/OAIGuestLinkRedeemRequest.h \
    $${PWD}/OAIGuestLinkRedeemResponse.h \
    $${PWD}/OAIHashes.h \
    $${PWD}/OAIIdentity.h \
    $${PWD}/OAIIdentitySet.h \
    $${PWD}/OAIImage.h \
    $${PWD}/OAIInvitation.h \
    $${PWD}/OAIInvitedUserMessageInfo.h \
    $${PWD}/OAIItemReference.h \
    $${PWD}/OAILivePhoto.h \
    $${PWD}/OAILockInfo.h \
    $${PWD}/OAIMember_Reference.h \
    $${PWD}/OAIMetricDefinition.h \
    $${PWD}/OAIMotionPhoto.h \
    $${PWD}/OAIObjectIdentity.h \
    $${PWD}/OAIOdata_error.h \
    $${PWD}/OAIOdata_error_detail.h \
    $${PWD}/OAIOdata_error_main.h \
    $${PWD}/OAIOpenGraphFile.h \
    $${PWD}/OAIPasswordProfile.h \
    $${PWD}/OAIPassword_change.h \
    $${PWD}/OAIPendingOperations.h \
    $${PWD}/OAIPendingOperations_pendingContentUpdate.h \
    $${PWD}/OAIPermission.h \
    $${PWD}/OAIPhoto.h \
    $${PWD}/OAIQuota.h \
    $${PWD}/OAIRecipient.h \
    $${PWD}/OAIRemoteItem.h \
    $${PWD}/OAISearchAggregation.h \
    $${PWD}/OAISearchBucket.h \
    $${PWD}/OAISearchHit.h \
    $${PWD}/OAISearchHitsContainer.h \
    $${PWD}/OAISearchMetric.h \
    $${PWD}/OAISearchQuery.h \
    $${PWD}/OAISearchQuery_200_response.h \
    $${PWD}/OAISearchQuery_request.h \
    $${PWD}/OAISearchRequest.h \
    $${PWD}/OAISearchResponse.h \
    $${PWD}/OAISharePointIdentitySet.h \
    $${PWD}/OAISharingInvitation.h \
    $${PWD}/OAISharingLink.h \
    $${PWD}/OAISharingLinkPassword.h \
    $${PWD}/OAISharingLinkType.h \
    $${PWD}/OAISignInActivity.h \
    $${PWD}/OAISortProperty.h \
    $${PWD}/OAISpecialFolder.h \
    $${PWD}/OAITagAssignment.h \
    $${PWD}/OAITagUnassignment.h \
    $${PWD}/OAIThumbnail.h \
    $${PWD}/OAIThumbnailSet.h \
    $${PWD}/OAITrash.h \
    $${PWD}/OAIUnifiedRoleDefinition.h \
    $${PWD}/OAIUnifiedRolePermission.h \
    $${PWD}/OAIUser.h \
    $${PWD}/OAIUserUpdate.h \
    $${PWD}/OAIVideo.h \
# APIs
    $${PWD}/OAIActivitiesApi.h \
    $${PWD}/OAIApplicationsApi.h \
    $${PWD}/OAIDriveItemApi.h \
    $${PWD}/OAIDrivesApi.h \
    $${PWD}/OAIDrivesGetDrivesApi.h \
    $${PWD}/OAIDrivesPermissionsApi.h \
    $${PWD}/OAIDrivesRootApi.h \
    $${PWD}/OAIEducationClassApi.h \
    $${PWD}/OAIEducationClassTeachersApi.h \
    $${PWD}/OAIEducationSchoolApi.h \
    $${PWD}/OAIEducationUserApi.h \
    $${PWD}/OAIGroupApi.h \
    $${PWD}/OAIGroupsApi.h \
    $${PWD}/OAIGuestLinksApi.h \
    $${PWD}/OAIInvitationsApi.h \
    $${PWD}/OAIMeChangepasswordApi.h \
    $${PWD}/OAIMeDriveApi.h \
    $${PWD}/OAIMeDriveRootApi.h \
    $${PWD}/OAIMeDriveRootChildrenApi.h \
    $${PWD}/OAIMeDrivesApi.h \
    $${PWD}/OAIMePhotoApi.h \
    $${PWD}/OAIMeUserApi.h \
    $${PWD}/OAIRoleManagementApi.h \
    $${PWD}/OAISearchApi.h \
    $${PWD}/OAITagsApi.h \
    $${PWD}/OAIUserApi.h \
    $${PWD}/OAIUserAppRoleAssignmentApi.h \
    $${PWD}/OAIUserPhotoApi.h \
    $${PWD}/OAIUserTeamworkApi.h \
    $${PWD}/OAIUsersApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAIActivity.cpp \
    $${PWD}/OAIActivityNotification.cpp \
    $${PWD}/OAIActivityTopic.cpp \
    $${PWD}/OAIActivity_template.cpp \
    $${PWD}/OAIActivity_times.cpp \
    $${PWD}/OAIAggregationOption.cpp \
    $${PWD}/OAIAppRole.cpp \
    $${PWD}/OAIAppRoleAssignment.cpp \
    $${PWD}/OAIApplication.cpp \
    $${PWD}/OAIAudio.cpp \
    $${PWD}/OAIBucketAggregationRange.cpp \
    $${PWD}/OAIBucketDefinition.cpp \
    $${PWD}/OAIClass_Member_Reference.cpp \
    $${PWD}/OAIClass_Reference.cpp \
    $${PWD}/OAIClass_Teacher_Reference.cpp \
    $${PWD}/OAICollection_of_activities.cpp \
    $${PWD}/OAICollection_of_appRoleAssignments.cpp \
    $${PWD}/OAICollection_of_applications.cpp \
    $${PWD}/OAICollection_of_class.cpp \
    $${PWD}/OAICollection_of_driveItems.cpp \
    $${PWD}/OAICollection_of_driveItems_1.cpp \
    $${PWD}/OAICollection_of_drives.cpp \
    $${PWD}/OAICollection_of_drives_1.cpp \
    $${PWD}/OAICollection_of_educationClass.cpp \
    $${PWD}/OAICollection_of_educationUser.cpp \
    $${PWD}/OAICollection_of_group.cpp \
    $${PWD}/OAICollection_of_invitations.cpp \
    $${PWD}/OAICollection_of_permissions.cpp \
    $${PWD}/OAICollection_of_permissions_with_allowed_values.cpp \
    $${PWD}/OAICollection_of_schools.cpp \
    $${PWD}/OAICollection_of_tags.cpp \
    $${PWD}/OAICollection_of_user.cpp \
    $${PWD}/OAICollection_of_users.cpp \
    $${PWD}/OAIDeleted.cpp \
    $${PWD}/OAIDrive.cpp \
    $${PWD}/OAIDriveItem.cpp \
    $${PWD}/OAIDriveItemCreateLink.cpp \
    $${PWD}/OAIDriveItemInvite.cpp \
    $${PWD}/OAIDriveRecipient.cpp \
    $${PWD}/OAIDriveUpdate.cpp \
    $${PWD}/OAIEducationClass.cpp \
    $${PWD}/OAIEducationSchool.cpp \
    $${PWD}/OAIEducationUser.cpp \
    $${PWD}/OAIEducationUser_Reference.cpp \
    $${PWD}/OAIEmailAddress.cpp \
    $${PWD}/OAIExportPersonalData_request.cpp \
    $${PWD}/OAIFileSystemInfo.cpp \
    $${PWD}/OAIFolder.cpp \
    $${PWD}/OAIFolderView.cpp \
    $${PWD}/OAIGeoCoordinates.cpp \
    $${PWD}/OAIGeohashDefinition.cpp \
    $${PWD}/OAIGroup.cpp \
    $${PWD}/OAIGuestLinkError.cpp \
    $${PWD}/OAIGuestLinkRedeemRequest.cpp \
    $${PWD}/OAIGuestLinkRedeemResponse.cpp \
    $${PWD}/OAIHashes.cpp \
    $${PWD}/OAIIdentity.cpp \
    $${PWD}/OAIIdentitySet.cpp \
    $${PWD}/OAIImage.cpp \
    $${PWD}/OAIInvitation.cpp \
    $${PWD}/OAIInvitedUserMessageInfo.cpp \
    $${PWD}/OAIItemReference.cpp \
    $${PWD}/OAILivePhoto.cpp \
    $${PWD}/OAILockInfo.cpp \
    $${PWD}/OAIMember_Reference.cpp \
    $${PWD}/OAIMetricDefinition.cpp \
    $${PWD}/OAIMotionPhoto.cpp \
    $${PWD}/OAIObjectIdentity.cpp \
    $${PWD}/OAIOdata_error.cpp \
    $${PWD}/OAIOdata_error_detail.cpp \
    $${PWD}/OAIOdata_error_main.cpp \
    $${PWD}/OAIOpenGraphFile.cpp \
    $${PWD}/OAIPasswordProfile.cpp \
    $${PWD}/OAIPassword_change.cpp \
    $${PWD}/OAIPendingOperations.cpp \
    $${PWD}/OAIPendingOperations_pendingContentUpdate.cpp \
    $${PWD}/OAIPermission.cpp \
    $${PWD}/OAIPhoto.cpp \
    $${PWD}/OAIQuota.cpp \
    $${PWD}/OAIRecipient.cpp \
    $${PWD}/OAIRemoteItem.cpp \
    $${PWD}/OAISearchAggregation.cpp \
    $${PWD}/OAISearchBucket.cpp \
    $${PWD}/OAISearchHit.cpp \
    $${PWD}/OAISearchHitsContainer.cpp \
    $${PWD}/OAISearchMetric.cpp \
    $${PWD}/OAISearchQuery.cpp \
    $${PWD}/OAISearchQuery_200_response.cpp \
    $${PWD}/OAISearchQuery_request.cpp \
    $${PWD}/OAISearchRequest.cpp \
    $${PWD}/OAISearchResponse.cpp \
    $${PWD}/OAISharePointIdentitySet.cpp \
    $${PWD}/OAISharingInvitation.cpp \
    $${PWD}/OAISharingLink.cpp \
    $${PWD}/OAISharingLinkPassword.cpp \
    $${PWD}/OAISharingLinkType.cpp \
    $${PWD}/OAISignInActivity.cpp \
    $${PWD}/OAISortProperty.cpp \
    $${PWD}/OAISpecialFolder.cpp \
    $${PWD}/OAITagAssignment.cpp \
    $${PWD}/OAITagUnassignment.cpp \
    $${PWD}/OAIThumbnail.cpp \
    $${PWD}/OAIThumbnailSet.cpp \
    $${PWD}/OAITrash.cpp \
    $${PWD}/OAIUnifiedRoleDefinition.cpp \
    $${PWD}/OAIUnifiedRolePermission.cpp \
    $${PWD}/OAIUser.cpp \
    $${PWD}/OAIUserUpdate.cpp \
    $${PWD}/OAIVideo.cpp \
# APIs
    $${PWD}/OAIActivitiesApi.cpp \
    $${PWD}/OAIApplicationsApi.cpp \
    $${PWD}/OAIDriveItemApi.cpp \
    $${PWD}/OAIDrivesApi.cpp \
    $${PWD}/OAIDrivesGetDrivesApi.cpp \
    $${PWD}/OAIDrivesPermissionsApi.cpp \
    $${PWD}/OAIDrivesRootApi.cpp \
    $${PWD}/OAIEducationClassApi.cpp \
    $${PWD}/OAIEducationClassTeachersApi.cpp \
    $${PWD}/OAIEducationSchoolApi.cpp \
    $${PWD}/OAIEducationUserApi.cpp \
    $${PWD}/OAIGroupApi.cpp \
    $${PWD}/OAIGroupsApi.cpp \
    $${PWD}/OAIGuestLinksApi.cpp \
    $${PWD}/OAIInvitationsApi.cpp \
    $${PWD}/OAIMeChangepasswordApi.cpp \
    $${PWD}/OAIMeDriveApi.cpp \
    $${PWD}/OAIMeDriveRootApi.cpp \
    $${PWD}/OAIMeDriveRootChildrenApi.cpp \
    $${PWD}/OAIMeDrivesApi.cpp \
    $${PWD}/OAIMePhotoApi.cpp \
    $${PWD}/OAIMeUserApi.cpp \
    $${PWD}/OAIRoleManagementApi.cpp \
    $${PWD}/OAISearchApi.cpp \
    $${PWD}/OAITagsApi.cpp \
    $${PWD}/OAIUserApi.cpp \
    $${PWD}/OAIUserAppRoleAssignmentApi.cpp \
    $${PWD}/OAIUserPhotoApi.cpp \
    $${PWD}/OAIUserTeamworkApi.cpp \
    $${PWD}/OAIUsersApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
