// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIActivityNotification.h
 *
 * An activity someone is notified about. 
 */

#ifndef OAIActivityNotification_H
#define OAIActivityNotification_H

#include <QJsonObject>

#include "OAIActivityTopic.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIActivityTopic;


class OAIActivityNotificationPrivate;

class OAIActivityNotification : public OAIObject {
public:
    OAIActivityNotification();
    OAIActivityNotification(const OAIActivityNotification &other);
    OAIActivityNotification(QString json);
    ~OAIActivityNotification() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIActivityTopic getTopic() const;
    void setTopic(const OAIActivityTopic &topic);
    bool is_topic_Set() const;
    bool is_topic_Valid() const;

    QString getActivityType() const;
    void setActivityType(const QString &activity_type);
    bool is_activity_type_Set() const;
    bool is_activity_type_Valid() const;

    QString getTeamsAppId() const;
    void setTeamsAppId(const QString &teams_app_id);
    bool is_teams_app_id_Set() const;
    bool is_teams_app_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIActivityNotification)
    QSharedPointer<OAIActivityNotificationPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIActivityNotification)

#endif // OAIActivityNotification_H
