// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIActivityNotification.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIActivityNotificationPrivate {
    friend class OAIActivityNotification;

     OAIActivityTopic topic;
     bool topic_isSet;
     bool topic_isValid;

     QString activity_type;
     bool activity_type_isSet;
     bool activity_type_isValid;

     QString teams_app_id;
     bool teams_app_id_isSet;
     bool teams_app_id_isValid;
};

OAIActivityNotification::OAIActivityNotification()
    : d_ptr()
{
}

OAIActivityNotification::OAIActivityNotification(const OAIActivityNotification& other)
    : d_ptr(other.d_ptr)
{
}

OAIActivityNotification::OAIActivityNotification(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIActivityNotification::~OAIActivityNotification() = default;

void OAIActivityNotification::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIActivityNotificationPrivate{});

        Q_D(OAIActivityNotification);


        d->topic_isSet = false;
        d->topic_isValid = false;

        d->activity_type_isSet = false;
        d->activity_type_isValid = false;

        d->teams_app_id_isSet = false;
        d->teams_app_id_isValid = false;
    }
}

void OAIActivityNotification::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIActivityNotification::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIActivityNotification);

    d->topic_isValid = ::OpenAPI::fromJsonValue(d->topic, json[QString("topic")]);
    d->topic_isSet = !json[QString("topic")].isNull() && d->topic_isValid;

    d->activity_type_isValid = ::OpenAPI::fromJsonValue(d->activity_type, json[QString("activityType")]);
    d->activity_type_isSet = !json[QString("activityType")].isNull() && d->activity_type_isValid;

    d->teams_app_id_isValid = ::OpenAPI::fromJsonValue(d->teams_app_id, json[QString("teamsAppId")]);
    d->teams_app_id_isSet = !json[QString("teamsAppId")].isNull() && d->teams_app_id_isValid;
}

QString OAIActivityNotification::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIActivityNotification::asJsonObject() const {
    Q_D(const OAIActivityNotification);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->topic.isSet()) {
        obj.insert(QString("topic"), ::OpenAPI::toJsonValue(d->topic));
    }
    if (d->activity_type_isSet) {
        obj.insert(QString("activityType"), ::OpenAPI::toJsonValue(d->activity_type));
    }
    if (d->teams_app_id_isSet) {
        obj.insert(QString("teamsAppId"), ::OpenAPI::toJsonValue(d->teams_app_id));
    }
    return obj;
}

OAIActivityTopic OAIActivityNotification::getTopic() const {
    Q_D(const OAIActivityNotification);
    if(!d){
        return {};
    }
    return d->topic;
}
void OAIActivityNotification::setTopic(const OAIActivityTopic &topic) {
    Q_D(OAIActivityNotification);
    Q_ASSERT(d);

    d->topic = topic;
    d->topic_isSet = true;
}

bool OAIActivityNotification::is_topic_Set() const{
    Q_D(const OAIActivityNotification);
    if(!d){
        return false;
    }

    return d->topic_isSet;
}

bool OAIActivityNotification::is_topic_Valid() const{
    Q_D(const OAIActivityNotification);
    if(!d){
        return false;
    }
    return d->topic_isValid;
}

QString OAIActivityNotification::getActivityType() const {
    Q_D(const OAIActivityNotification);
    if(!d){
        return {};
    }
    return d->activity_type;
}
void OAIActivityNotification::setActivityType(const QString &activity_type) {
    Q_D(OAIActivityNotification);
    Q_ASSERT(d);

    d->activity_type = activity_type;
    d->activity_type_isSet = true;
}

bool OAIActivityNotification::is_activity_type_Set() const{
    Q_D(const OAIActivityNotification);
    if(!d){
        return false;
    }

    return d->activity_type_isSet;
}

bool OAIActivityNotification::is_activity_type_Valid() const{
    Q_D(const OAIActivityNotification);
    if(!d){
        return false;
    }
    return d->activity_type_isValid;
}

QString OAIActivityNotification::getTeamsAppId() const {
    Q_D(const OAIActivityNotification);
    if(!d){
        return {};
    }
    return d->teams_app_id;
}
void OAIActivityNotification::setTeamsAppId(const QString &teams_app_id) {
    Q_D(OAIActivityNotification);
    Q_ASSERT(d);

    d->teams_app_id = teams_app_id;
    d->teams_app_id_isSet = true;
}

bool OAIActivityNotification::is_teams_app_id_Set() const{
    Q_D(const OAIActivityNotification);
    if(!d){
        return false;
    }

    return d->teams_app_id_isSet;
}

bool OAIActivityNotification::is_teams_app_id_Valid() const{
    Q_D(const OAIActivityNotification);
    if(!d){
        return false;
    }
    return d->teams_app_id_isValid;
}

bool OAIActivityNotification::isSet() const {
    Q_D(const OAIActivityNotification);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->topic.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (d->activity_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->teams_app_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIActivityNotification::isValid() const {
    Q_D(const OAIActivityNotification);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->topic_isValid && d->activity_type_isValid && d->teams_app_id_isValid && true;
}

} // namespace OpenAPI
