// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIAggregationOption.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIAggregationOptionPrivate {
    friend class OAIAggregationOption;

     QString field;
     bool field_isSet;
     bool field_isValid;

     qint32 size;
     bool size_isSet;
     bool size_isValid;

     OAIBucketDefinition bucket_definition;
     bool bucket_definition_isSet;
     bool bucket_definition_isValid;

     QList<OAIAggregationOption> libre_graph_sub_aggregations;
     bool libre_graph_sub_aggregations_isSet;
     bool libre_graph_sub_aggregations_isValid;

     OAIMetricDefinition libre_graph_metric_definition;
     bool libre_graph_metric_definition_isSet;
     bool libre_graph_metric_definition_isValid;
};

OAIAggregationOption::OAIAggregationOption()
    : d_ptr()
{
}

OAIAggregationOption::OAIAggregationOption(const OAIAggregationOption& other)
    : d_ptr(other.d_ptr)
{
}

OAIAggregationOption::OAIAggregationOption(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIAggregationOption::~OAIAggregationOption() = default;

void OAIAggregationOption::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIAggregationOptionPrivate{});

        Q_D(OAIAggregationOption);


        d->field_isSet = false;
        d->field_isValid = false;

        d->size_isSet = false;
        d->size_isValid = false;

        d->bucket_definition_isSet = false;
        d->bucket_definition_isValid = false;

        d->libre_graph_sub_aggregations_isSet = false;
        d->libre_graph_sub_aggregations_isValid = false;

        d->libre_graph_metric_definition_isSet = false;
        d->libre_graph_metric_definition_isValid = false;
    }
}

void OAIAggregationOption::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIAggregationOption::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIAggregationOption);

    d->field_isValid = ::OpenAPI::fromJsonValue(d->field, json[QString("field")]);
    d->field_isSet = !json[QString("field")].isNull() && d->field_isValid;

    d->size_isValid = ::OpenAPI::fromJsonValue(d->size, json[QString("size")]);
    d->size_isSet = !json[QString("size")].isNull() && d->size_isValid;

    d->bucket_definition_isValid = ::OpenAPI::fromJsonValue(d->bucket_definition, json[QString("bucketDefinition")]);
    d->bucket_definition_isSet = !json[QString("bucketDefinition")].isNull() && d->bucket_definition_isValid;

    d->libre_graph_sub_aggregations_isValid = ::OpenAPI::fromJsonValue(d->libre_graph_sub_aggregations, json[QString("@libre.graph.subAggregations")]);
    d->libre_graph_sub_aggregations_isSet = !json[QString("@libre.graph.subAggregations")].isNull() && d->libre_graph_sub_aggregations_isValid;

    d->libre_graph_metric_definition_isValid = ::OpenAPI::fromJsonValue(d->libre_graph_metric_definition, json[QString("@libre.graph.metricDefinition")]);
    d->libre_graph_metric_definition_isSet = !json[QString("@libre.graph.metricDefinition")].isNull() && d->libre_graph_metric_definition_isValid;
}

QString OAIAggregationOption::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIAggregationOption::asJsonObject() const {
    Q_D(const OAIAggregationOption);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->field_isSet) {
        obj.insert(QString("field"), ::OpenAPI::toJsonValue(d->field));
    }
    if (d->size_isSet) {
        obj.insert(QString("size"), ::OpenAPI::toJsonValue(d->size));
    }
    if (d->bucket_definition.isSet()) {
        obj.insert(QString("bucketDefinition"), ::OpenAPI::toJsonValue(d->bucket_definition));
    }
    if (d->libre_graph_sub_aggregations.size() > 0) {
        obj.insert(QString("@libre.graph.subAggregations"), ::OpenAPI::toJsonValue(d->libre_graph_sub_aggregations));
    }
    if (d->libre_graph_metric_definition.isSet()) {
        obj.insert(QString("@libre.graph.metricDefinition"), ::OpenAPI::toJsonValue(d->libre_graph_metric_definition));
    }
    return obj;
}

QString OAIAggregationOption::getField() const {
    Q_D(const OAIAggregationOption);
    if(!d){
        return {};
    }
    return d->field;
}
void OAIAggregationOption::setField(const QString &field) {
    Q_D(OAIAggregationOption);
    Q_ASSERT(d);

    d->field = field;
    d->field_isSet = true;
}

bool OAIAggregationOption::is_field_Set() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }

    return d->field_isSet;
}

bool OAIAggregationOption::is_field_Valid() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }
    return d->field_isValid;
}

qint32 OAIAggregationOption::getSize() const {
    Q_D(const OAIAggregationOption);
    if(!d){
        return {};
    }
    return d->size;
}
void OAIAggregationOption::setSize(const qint32 &size) {
    Q_D(OAIAggregationOption);
    Q_ASSERT(d);

    d->size = size;
    d->size_isSet = true;
}

bool OAIAggregationOption::is_size_Set() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }

    return d->size_isSet;
}

bool OAIAggregationOption::is_size_Valid() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }
    return d->size_isValid;
}

OAIBucketDefinition OAIAggregationOption::getBucketDefinition() const {
    Q_D(const OAIAggregationOption);
    if(!d){
        return {};
    }
    return d->bucket_definition;
}
void OAIAggregationOption::setBucketDefinition(const OAIBucketDefinition &bucket_definition) {
    Q_D(OAIAggregationOption);
    Q_ASSERT(d);

    d->bucket_definition = bucket_definition;
    d->bucket_definition_isSet = true;
}

bool OAIAggregationOption::is_bucket_definition_Set() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }

    return d->bucket_definition_isSet;
}

bool OAIAggregationOption::is_bucket_definition_Valid() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }
    return d->bucket_definition_isValid;
}

QList<OAIAggregationOption> OAIAggregationOption::getLibreGraphSubAggregations() const {
    Q_D(const OAIAggregationOption);
    if(!d){
        return {};
    }
    return d->libre_graph_sub_aggregations;
}
void OAIAggregationOption::setLibreGraphSubAggregations(const QList<OAIAggregationOption> &libre_graph_sub_aggregations) {
    Q_D(OAIAggregationOption);
    Q_ASSERT(d);

    d->libre_graph_sub_aggregations = libre_graph_sub_aggregations;
    d->libre_graph_sub_aggregations_isSet = true;
}

bool OAIAggregationOption::is_libre_graph_sub_aggregations_Set() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }

    return d->libre_graph_sub_aggregations_isSet;
}

bool OAIAggregationOption::is_libre_graph_sub_aggregations_Valid() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }
    return d->libre_graph_sub_aggregations_isValid;
}

OAIMetricDefinition OAIAggregationOption::getLibreGraphMetricDefinition() const {
    Q_D(const OAIAggregationOption);
    if(!d){
        return {};
    }
    return d->libre_graph_metric_definition;
}
void OAIAggregationOption::setLibreGraphMetricDefinition(const OAIMetricDefinition &libre_graph_metric_definition) {
    Q_D(OAIAggregationOption);
    Q_ASSERT(d);

    d->libre_graph_metric_definition = libre_graph_metric_definition;
    d->libre_graph_metric_definition_isSet = true;
}

bool OAIAggregationOption::is_libre_graph_metric_definition_Set() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }

    return d->libre_graph_metric_definition_isSet;
}

bool OAIAggregationOption::is_libre_graph_metric_definition_Valid() const{
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }
    return d->libre_graph_metric_definition_isValid;
}

bool OAIAggregationOption::isSet() const {
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->field_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->size_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->bucket_definition.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (d->libre_graph_sub_aggregations.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->libre_graph_metric_definition.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIAggregationOption::isValid() const {
    Q_D(const OAIAggregationOption);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->field_isValid && true;
}

} // namespace OpenAPI
