// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIActivityTopic.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIActivityTopicPrivate {
    friend class OAIActivityTopic;

     QString source;
     bool source_isSet;
     bool source_isValid;

     QString value;
     bool value_isSet;
     bool value_isValid;
};

OAIActivityTopic::OAIActivityTopic()
    : d_ptr()
{
}

OAIActivityTopic::OAIActivityTopic(const OAIActivityTopic& other)
    : d_ptr(other.d_ptr)
{
}

OAIActivityTopic::OAIActivityTopic(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIActivityTopic::~OAIActivityTopic() = default;

void OAIActivityTopic::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIActivityTopicPrivate{});

        Q_D(OAIActivityTopic);


        d->source_isSet = false;
        d->source_isValid = false;

        d->value_isSet = false;
        d->value_isValid = false;
    }
}

void OAIActivityTopic::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIActivityTopic::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIActivityTopic);

    d->source_isValid = ::OpenAPI::fromJsonValue(d->source, json[QString("source")]);
    d->source_isSet = !json[QString("source")].isNull() && d->source_isValid;

    d->value_isValid = ::OpenAPI::fromJsonValue(d->value, json[QString("value")]);
    d->value_isSet = !json[QString("value")].isNull() && d->value_isValid;
}

QString OAIActivityTopic::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIActivityTopic::asJsonObject() const {
    Q_D(const OAIActivityTopic);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->source_isSet) {
        obj.insert(QString("source"), ::OpenAPI::toJsonValue(d->source));
    }
    if (d->value_isSet) {
        obj.insert(QString("value"), ::OpenAPI::toJsonValue(d->value));
    }
    return obj;
}

QString OAIActivityTopic::getSource() const {
    Q_D(const OAIActivityTopic);
    if(!d){
        return {};
    }
    return d->source;
}
void OAIActivityTopic::setSource(const QString &source) {
    Q_D(OAIActivityTopic);
    Q_ASSERT(d);

    d->source = source;
    d->source_isSet = true;
}

bool OAIActivityTopic::is_source_Set() const{
    Q_D(const OAIActivityTopic);
    if(!d){
        return false;
    }

    return d->source_isSet;
}

bool OAIActivityTopic::is_source_Valid() const{
    Q_D(const OAIActivityTopic);
    if(!d){
        return false;
    }
    return d->source_isValid;
}

QString OAIActivityTopic::getValue() const {
    Q_D(const OAIActivityTopic);
    if(!d){
        return {};
    }
    return d->value;
}
void OAIActivityTopic::setValue(const QString &value) {
    Q_D(OAIActivityTopic);
    Q_ASSERT(d);

    d->value = value;
    d->value_isSet = true;
}

bool OAIActivityTopic::is_value_Set() const{
    Q_D(const OAIActivityTopic);
    if(!d){
        return false;
    }

    return d->value_isSet;
}

bool OAIActivityTopic::is_value_Valid() const{
    Q_D(const OAIActivityTopic);
    if(!d){
        return false;
    }
    return d->value_isValid;
}

bool OAIActivityTopic::isSet() const {
    Q_D(const OAIActivityTopic);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->source_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->value_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIActivityTopic::isValid() const {
    Q_D(const OAIActivityTopic);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->source_isValid && d->value_isValid && true;
}

} // namespace OpenAPI
