// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAggregationOption.h
 *
 * Specifies an aggregation that should be computed and returned alongside search results. Follows the [MS Graph aggregationOption](https://learn.microsoft.com/en-us/graph/api/resources/aggregationoption) resource type.  For string fields, terms aggregations return the distinct values and their counts. For numeric and date fields, range aggregations can be defined using the &#x60;ranges&#x60; property of &#x60;bucketDefinition&#x60;.  At most one of &#x60;bucketDefinition&#x60;, &#x60;@libre.graph.metricDefinition&#x60; and &#x60;@libre.graph.geohashDefinition&#x60; may be set; requests specifying more than one are rejected with &#x60;invalidRequest&#x60;. 
 */

#ifndef OAIAggregationOption_H
#define OAIAggregationOption_H

#include <QJsonObject>

#include "OAIBucketDefinition.h"
#include "OAIGeohashDefinition.h"
#include "OAIMetricDefinition.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIBucketDefinition;
class OAIMetricDefinition;
class OAIGeohashDefinition;


class OAIAggregationOptionPrivate;

class OAIAggregationOption : public OAIObject {
public:
    OAIAggregationOption();
    OAIAggregationOption(const OAIAggregationOption &other);
    OAIAggregationOption(QString json);
    ~OAIAggregationOption() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getField() const;
    void setField(const QString &field);
    bool is_field_Set() const;
    bool is_field_Valid() const;

    qint32 getSize() const;
    void setSize(const qint32 &size);
    bool is_size_Set() const;
    bool is_size_Valid() const;

    OAIBucketDefinition getBucketDefinition() const;
    void setBucketDefinition(const OAIBucketDefinition &bucket_definition);
    bool is_bucket_definition_Set() const;
    bool is_bucket_definition_Valid() const;

    QList<OAIAggregationOption> getLibreGraphSubAggregations() const;
    void setLibreGraphSubAggregations(const QList<OAIAggregationOption> &libre_graph_sub_aggregations);
    bool is_libre_graph_sub_aggregations_Set() const;
    bool is_libre_graph_sub_aggregations_Valid() const;

    OAIMetricDefinition getLibreGraphMetricDefinition() const;
    void setLibreGraphMetricDefinition(const OAIMetricDefinition &libre_graph_metric_definition);
    bool is_libre_graph_metric_definition_Set() const;
    bool is_libre_graph_metric_definition_Valid() const;

    OAIGeohashDefinition getLibreGraphGeohashDefinition() const;
    void setLibreGraphGeohashDefinition(const OAIGeohashDefinition &libre_graph_geohash_definition);
    bool is_libre_graph_geohash_definition_Set() const;
    bool is_libre_graph_geohash_definition_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIAggregationOption)
    QSharedPointer<OAIAggregationOptionPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAggregationOption)

#endif // OAIAggregationOption_H
