// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIBucketAggregationRange.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIBucketAggregationRangePrivate {
    friend class OAIBucketAggregationRange;

     QString from;
     bool from_isSet;
     bool from_isValid;

     QString to;
     bool to_isSet;
     bool to_isValid;
};

OAIBucketAggregationRange::OAIBucketAggregationRange()
    : d_ptr()
{
}

OAIBucketAggregationRange::OAIBucketAggregationRange(const OAIBucketAggregationRange& other)
    : d_ptr(other.d_ptr)
{
}

OAIBucketAggregationRange::OAIBucketAggregationRange(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIBucketAggregationRange::~OAIBucketAggregationRange() = default;

void OAIBucketAggregationRange::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIBucketAggregationRangePrivate{});

        Q_D(OAIBucketAggregationRange);


        d->from_isSet = false;
        d->from_isValid = false;

        d->to_isSet = false;
        d->to_isValid = false;
    }
}

void OAIBucketAggregationRange::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIBucketAggregationRange::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIBucketAggregationRange);

    d->from_isValid = ::OpenAPI::fromJsonValue(d->from, json[QString("from")]);
    d->from_isSet = !json[QString("from")].isNull() && d->from_isValid;

    d->to_isValid = ::OpenAPI::fromJsonValue(d->to, json[QString("to")]);
    d->to_isSet = !json[QString("to")].isNull() && d->to_isValid;
}

QString OAIBucketAggregationRange::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIBucketAggregationRange::asJsonObject() const {
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->from_isSet) {
        obj.insert(QString("from"), ::OpenAPI::toJsonValue(d->from));
    }
    if (d->to_isSet) {
        obj.insert(QString("to"), ::OpenAPI::toJsonValue(d->to));
    }
    return obj;
}

QString OAIBucketAggregationRange::getFrom() const {
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return {};
    }
    return d->from;
}
void OAIBucketAggregationRange::setFrom(const QString &from) {
    Q_D(OAIBucketAggregationRange);
    Q_ASSERT(d);

    d->from = from;
    d->from_isSet = true;
}

bool OAIBucketAggregationRange::is_from_Set() const{
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return false;
    }

    return d->from_isSet;
}

bool OAIBucketAggregationRange::is_from_Valid() const{
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return false;
    }
    return d->from_isValid;
}

QString OAIBucketAggregationRange::getTo() const {
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return {};
    }
    return d->to;
}
void OAIBucketAggregationRange::setTo(const QString &to) {
    Q_D(OAIBucketAggregationRange);
    Q_ASSERT(d);

    d->to = to;
    d->to_isSet = true;
}

bool OAIBucketAggregationRange::is_to_Set() const{
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return false;
    }

    return d->to_isSet;
}

bool OAIBucketAggregationRange::is_to_Valid() const{
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return false;
    }
    return d->to_isValid;
}

bool OAIBucketAggregationRange::isSet() const {
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->from_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->to_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIBucketAggregationRange::isValid() const {
    Q_D(const OAIBucketAggregationRange);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
