// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBucketAggregationRange.h
 *
 * Specifies the lower and upper bound to compute a range aggregation bucket. At least one of &#x60;from&#x60; or &#x60;to&#x60; must be provided. 
 */

#ifndef OAIBucketAggregationRange_H
#define OAIBucketAggregationRange_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIBucketAggregationRangePrivate;

class OAIBucketAggregationRange : public OAIObject {
public:
    OAIBucketAggregationRange();
    OAIBucketAggregationRange(const OAIBucketAggregationRange &other);
    OAIBucketAggregationRange(QString json);
    ~OAIBucketAggregationRange() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getFrom() const;
    void setFrom(const QString &from);
    bool is_from_Set() const;
    bool is_from_Valid() const;

    QString getTo() const;
    void setTo(const QString &to);
    bool is_to_Set() const;
    bool is_to_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIBucketAggregationRange)
    QSharedPointer<OAIBucketAggregationRangePrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIBucketAggregationRange)

#endif // OAIBucketAggregationRange_H
