// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBucketDefinition.h
 *
 * Provides the details of how to generate the aggregation buckets in the response. Follows the [MS Graph bucketAggregationDefinition](https://learn.microsoft.com/en-us/graph/api/resources/bucketaggregationdefinition) resource type. 
 */

#ifndef OAIBucketDefinition_H
#define OAIBucketDefinition_H

#include <QJsonObject>

#include "OAIBucketAggregationRange.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIBucketAggregationRange;


class OAIBucketDefinitionPrivate;

class OAIBucketDefinition : public OAIObject {
public:
    OAIBucketDefinition();
    OAIBucketDefinition(const OAIBucketDefinition &other);
    OAIBucketDefinition(QString json);
    ~OAIBucketDefinition() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getSortBy() const;
    void setSortBy(const QString &sort_by);
    bool is_sort_by_Set() const;
    bool is_sort_by_Valid() const;

    bool isIsDescending() const;
    void setIsDescending(const bool &is_descending);
    bool is_is_descending_Set() const;
    bool is_is_descending_Valid() const;

    qint32 getMinimumCount() const;
    void setMinimumCount(const qint32 &minimum_count);
    bool is_minimum_count_Set() const;
    bool is_minimum_count_Valid() const;

    QList<OAIBucketAggregationRange> getRanges() const;
    void setRanges(const QList<OAIBucketAggregationRange> &ranges);
    bool is_ranges_Set() const;
    bool is_ranges_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIBucketDefinition)
    QSharedPointer<OAIBucketDefinitionPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIBucketDefinition)

#endif // OAIBucketDefinition_H
