// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIBucketDefinition.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIBucketDefinitionPrivate {
    friend class OAIBucketDefinition;

     QString sort_by;
     bool sort_by_isSet;
     bool sort_by_isValid;

     bool is_descending;
     bool is_descending_isSet;
     bool is_descending_isValid;

     qint32 minimum_count;
     bool minimum_count_isSet;
     bool minimum_count_isValid;

     QList<OAIBucketAggregationRange> ranges;
     bool ranges_isSet;
     bool ranges_isValid;
};

OAIBucketDefinition::OAIBucketDefinition()
    : d_ptr()
{
}

OAIBucketDefinition::OAIBucketDefinition(const OAIBucketDefinition& other)
    : d_ptr(other.d_ptr)
{
}

OAIBucketDefinition::OAIBucketDefinition(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIBucketDefinition::~OAIBucketDefinition() = default;

void OAIBucketDefinition::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIBucketDefinitionPrivate{});

        Q_D(OAIBucketDefinition);


        d->sort_by_isSet = false;
        d->sort_by_isValid = false;

        d->is_descending_isSet = false;
        d->is_descending_isValid = false;

        d->minimum_count_isSet = false;
        d->minimum_count_isValid = false;

        d->ranges_isSet = false;
        d->ranges_isValid = false;
    }
}

void OAIBucketDefinition::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIBucketDefinition::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIBucketDefinition);

    d->sort_by_isValid = ::OpenAPI::fromJsonValue(d->sort_by, json[QString("sortBy")]);
    d->sort_by_isSet = !json[QString("sortBy")].isNull() && d->sort_by_isValid;

    d->is_descending_isValid = ::OpenAPI::fromJsonValue(d->is_descending, json[QString("isDescending")]);
    d->is_descending_isSet = !json[QString("isDescending")].isNull() && d->is_descending_isValid;

    d->minimum_count_isValid = ::OpenAPI::fromJsonValue(d->minimum_count, json[QString("minimumCount")]);
    d->minimum_count_isSet = !json[QString("minimumCount")].isNull() && d->minimum_count_isValid;

    d->ranges_isValid = ::OpenAPI::fromJsonValue(d->ranges, json[QString("ranges")]);
    d->ranges_isSet = !json[QString("ranges")].isNull() && d->ranges_isValid;
}

QString OAIBucketDefinition::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIBucketDefinition::asJsonObject() const {
    Q_D(const OAIBucketDefinition);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->sort_by_isSet) {
        obj.insert(QString("sortBy"), ::OpenAPI::toJsonValue(d->sort_by));
    }
    if (d->is_descending_isSet) {
        obj.insert(QString("isDescending"), ::OpenAPI::toJsonValue(d->is_descending));
    }
    if (d->minimum_count_isSet) {
        obj.insert(QString("minimumCount"), ::OpenAPI::toJsonValue(d->minimum_count));
    }
    if (d->ranges.size() > 0) {
        obj.insert(QString("ranges"), ::OpenAPI::toJsonValue(d->ranges));
    }
    return obj;
}

QString OAIBucketDefinition::getSortBy() const {
    Q_D(const OAIBucketDefinition);
    if(!d){
        return {};
    }
    return d->sort_by;
}
void OAIBucketDefinition::setSortBy(const QString &sort_by) {
    Q_D(OAIBucketDefinition);
    Q_ASSERT(d);

    d->sort_by = sort_by;
    d->sort_by_isSet = true;
}

bool OAIBucketDefinition::is_sort_by_Set() const{
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }

    return d->sort_by_isSet;
}

bool OAIBucketDefinition::is_sort_by_Valid() const{
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }
    return d->sort_by_isValid;
}

bool OAIBucketDefinition::isIsDescending() const {
    Q_D(const OAIBucketDefinition);
    if(!d){
        return {};
    }
    return d->is_descending;
}
void OAIBucketDefinition::setIsDescending(const bool &is_descending) {
    Q_D(OAIBucketDefinition);
    Q_ASSERT(d);

    d->is_descending = is_descending;
    d->is_descending_isSet = true;
}

bool OAIBucketDefinition::is_is_descending_Set() const{
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }

    return d->is_descending_isSet;
}

bool OAIBucketDefinition::is_is_descending_Valid() const{
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }
    return d->is_descending_isValid;
}

qint32 OAIBucketDefinition::getMinimumCount() const {
    Q_D(const OAIBucketDefinition);
    if(!d){
        return {};
    }
    return d->minimum_count;
}
void OAIBucketDefinition::setMinimumCount(const qint32 &minimum_count) {
    Q_D(OAIBucketDefinition);
    Q_ASSERT(d);

    d->minimum_count = minimum_count;
    d->minimum_count_isSet = true;
}

bool OAIBucketDefinition::is_minimum_count_Set() const{
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }

    return d->minimum_count_isSet;
}

bool OAIBucketDefinition::is_minimum_count_Valid() const{
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }
    return d->minimum_count_isValid;
}

QList<OAIBucketAggregationRange> OAIBucketDefinition::getRanges() const {
    Q_D(const OAIBucketDefinition);
    if(!d){
        return {};
    }
    return d->ranges;
}
void OAIBucketDefinition::setRanges(const QList<OAIBucketAggregationRange> &ranges) {
    Q_D(OAIBucketDefinition);
    Q_ASSERT(d);

    d->ranges = ranges;
    d->ranges_isSet = true;
}

bool OAIBucketDefinition::is_ranges_Set() const{
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }

    return d->ranges_isSet;
}

bool OAIBucketDefinition::is_ranges_Valid() const{
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }
    return d->ranges_isValid;
}

bool OAIBucketDefinition::isSet() const {
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->sort_by_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->is_descending_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->minimum_count_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->ranges.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIBucketDefinition::isValid() const {
    Q_D(const OAIBucketDefinition);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->sort_by_isValid && true;
}

} // namespace OpenAPI
