// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIEmailAddress.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIEmailAddressPrivate {
    friend class OAIEmailAddress;

     QString address;
     bool address_isSet;
     bool address_isValid;

     QString name;
     bool name_isSet;
     bool name_isValid;
};

OAIEmailAddress::OAIEmailAddress()
    : d_ptr()
{
}

OAIEmailAddress::OAIEmailAddress(const OAIEmailAddress& other)
    : d_ptr(other.d_ptr)
{
}

OAIEmailAddress::OAIEmailAddress(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIEmailAddress::~OAIEmailAddress() = default;

void OAIEmailAddress::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIEmailAddressPrivate{});

        Q_D(OAIEmailAddress);


        d->address_isSet = false;
        d->address_isValid = false;

        d->name_isSet = false;
        d->name_isValid = false;
    }
}

void OAIEmailAddress::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIEmailAddress::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIEmailAddress);

    d->address_isValid = ::OpenAPI::fromJsonValue(d->address, json[QString("address")]);
    d->address_isSet = !json[QString("address")].isNull() && d->address_isValid;

    d->name_isValid = ::OpenAPI::fromJsonValue(d->name, json[QString("name")]);
    d->name_isSet = !json[QString("name")].isNull() && d->name_isValid;
}

QString OAIEmailAddress::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIEmailAddress::asJsonObject() const {
    Q_D(const OAIEmailAddress);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->address_isSet) {
        obj.insert(QString("address"), ::OpenAPI::toJsonValue(d->address));
    }
    if (d->name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(d->name));
    }
    return obj;
}

QString OAIEmailAddress::getAddress() const {
    Q_D(const OAIEmailAddress);
    if(!d){
        return {};
    }
    return d->address;
}
void OAIEmailAddress::setAddress(const QString &address) {
    Q_D(OAIEmailAddress);
    Q_ASSERT(d);

    d->address = address;
    d->address_isSet = true;
}

bool OAIEmailAddress::is_address_Set() const{
    Q_D(const OAIEmailAddress);
    if(!d){
        return false;
    }

    return d->address_isSet;
}

bool OAIEmailAddress::is_address_Valid() const{
    Q_D(const OAIEmailAddress);
    if(!d){
        return false;
    }
    return d->address_isValid;
}

QString OAIEmailAddress::getName() const {
    Q_D(const OAIEmailAddress);
    if(!d){
        return {};
    }
    return d->name;
}
void OAIEmailAddress::setName(const QString &name) {
    Q_D(OAIEmailAddress);
    Q_ASSERT(d);

    d->name = name;
    d->name_isSet = true;
}

bool OAIEmailAddress::is_name_Set() const{
    Q_D(const OAIEmailAddress);
    if(!d){
        return false;
    }

    return d->name_isSet;
}

bool OAIEmailAddress::is_name_Valid() const{
    Q_D(const OAIEmailAddress);
    if(!d){
        return false;
    }
    return d->name_isValid;
}

bool OAIEmailAddress::isSet() const {
    Q_D(const OAIEmailAddress);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->address_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIEmailAddress::isValid() const {
    Q_D(const OAIEmailAddress);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
