// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGeohashDefinition.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIGeohashDefinitionPrivate {
    friend class OAIGeohashDefinition;

     qint32 precision;
     bool precision_isSet;
     bool precision_isValid;
};

OAIGeohashDefinition::OAIGeohashDefinition()
    : d_ptr()
{
}

OAIGeohashDefinition::OAIGeohashDefinition(const OAIGeohashDefinition& other)
    : d_ptr(other.d_ptr)
{
}

OAIGeohashDefinition::OAIGeohashDefinition(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIGeohashDefinition::~OAIGeohashDefinition() = default;

void OAIGeohashDefinition::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIGeohashDefinitionPrivate{});

        Q_D(OAIGeohashDefinition);


        d->precision_isSet = false;
        d->precision_isValid = false;
    }
}

void OAIGeohashDefinition::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGeohashDefinition::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIGeohashDefinition);

    d->precision_isValid = ::OpenAPI::fromJsonValue(d->precision, json[QString("precision")]);
    d->precision_isSet = !json[QString("precision")].isNull() && d->precision_isValid;
}

QString OAIGeohashDefinition::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGeohashDefinition::asJsonObject() const {
    Q_D(const OAIGeohashDefinition);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->precision_isSet) {
        obj.insert(QString("precision"), ::OpenAPI::toJsonValue(d->precision));
    }
    return obj;
}

qint32 OAIGeohashDefinition::getPrecision() const {
    Q_D(const OAIGeohashDefinition);
    if(!d){
        return {};
    }
    return d->precision;
}
void OAIGeohashDefinition::setPrecision(const qint32 &precision) {
    Q_D(OAIGeohashDefinition);
    Q_ASSERT(d);

    d->precision = precision;
    d->precision_isSet = true;
}

bool OAIGeohashDefinition::is_precision_Set() const{
    Q_D(const OAIGeohashDefinition);
    if(!d){
        return false;
    }

    return d->precision_isSet;
}

bool OAIGeohashDefinition::is_precision_Valid() const{
    Q_D(const OAIGeohashDefinition);
    if(!d){
        return false;
    }
    return d->precision_isValid;
}

bool OAIGeohashDefinition::isSet() const {
    Q_D(const OAIGeohashDefinition);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->precision_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGeohashDefinition::isValid() const {
    Q_D(const OAIGeohashDefinition);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->precision_isValid && true;
}

} // namespace OpenAPI
