// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIGuestLinkVerifyPinRequest.h
 *
 * Request body for verifying a guest link PIN.
 */

#ifndef OAIGuestLinkVerifyPinRequest_H
#define OAIGuestLinkVerifyPinRequest_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIGuestLinkVerifyPinRequestPrivate;

class OAIGuestLinkVerifyPinRequest : public OAIObject {
public:
    OAIGuestLinkVerifyPinRequest();
    OAIGuestLinkVerifyPinRequest(const OAIGuestLinkVerifyPinRequest &other);
    OAIGuestLinkVerifyPinRequest(QString json);
    ~OAIGuestLinkVerifyPinRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPin() const;
    void setPin(const QString &pin);
    bool is_pin_Set() const;
    bool is_pin_Valid() const;

    QString getPermissionId() const;
    void setPermissionId(const QString &permission_id);
    bool is_permission_id_Set() const;
    bool is_permission_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIGuestLinkVerifyPinRequest)
    QSharedPointer<OAIGuestLinkVerifyPinRequestPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIGuestLinkVerifyPinRequest)

#endif // OAIGuestLinkVerifyPinRequest_H
