// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIGeohashDefinition.h
 *
 * Provides the details of how to compute a geohash-grid aggregation over &#x60;field&#x60;, which must resolve to a geo-point field (e.g. &#x60;location&#x60;). When set on an &#x60;aggregationOption&#x60;, each &#x60;searchBucket&#x60; of the corresponding &#x60;searchAggregation&#x60; carries a geohash cell as its &#x60;key&#x60;, with &#x60;count&#x60; holding the number of matches in the cell, suitable for density/heatmap rendering. &#x60;size&#x60; limits the buckets to the top N cells by count. Libregraph extension not present in MS Graph. 
 */

#ifndef OAIGeohashDefinition_H
#define OAIGeohashDefinition_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIGeohashDefinitionPrivate;

class OAIGeohashDefinition : public OAIObject {
public:
    OAIGeohashDefinition();
    OAIGeohashDefinition(const OAIGeohashDefinition &other);
    OAIGeohashDefinition(QString json);
    ~OAIGeohashDefinition() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getPrecision() const;
    void setPrecision(const qint32 &precision);
    bool is_precision_Set() const;
    bool is_precision_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIGeohashDefinition)
    QSharedPointer<OAIGeohashDefinitionPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIGeohashDefinition)

#endif // OAIGeohashDefinition_H
