// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIGuestLinkSessionResponse.h
 *
 * Response body for a successful guest link authentication: the share (permission) id the guest was invited to. A session cookie is set via the Set-Cookie header.
 */

#ifndef OAIGuestLinkSessionResponse_H
#define OAIGuestLinkSessionResponse_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIGuestLinkSessionResponsePrivate;

class OAIGuestLinkSessionResponse : public OAIObject {
public:
    OAIGuestLinkSessionResponse();
    OAIGuestLinkSessionResponse(const OAIGuestLinkSessionResponse &other);
    OAIGuestLinkSessionResponse(QString json);
    ~OAIGuestLinkSessionResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPermissionId() const;
    void setPermissionId(const QString &permission_id);
    bool is_permission_id_Set() const;
    bool is_permission_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIGuestLinkSessionResponse)
    QSharedPointer<OAIGuestLinkSessionResponsePrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIGuestLinkSessionResponse)

#endif // OAIGuestLinkSessionResponse_H
