// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGuestLinkVerifyPinRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIGuestLinkVerifyPinRequestPrivate {
    friend class OAIGuestLinkVerifyPinRequest;

     QString pin;
     bool pin_isSet;
     bool pin_isValid;

     QString permission_id;
     bool permission_id_isSet;
     bool permission_id_isValid;
};

OAIGuestLinkVerifyPinRequest::OAIGuestLinkVerifyPinRequest()
    : d_ptr()
{
}

OAIGuestLinkVerifyPinRequest::OAIGuestLinkVerifyPinRequest(const OAIGuestLinkVerifyPinRequest& other)
    : d_ptr(other.d_ptr)
{
}

OAIGuestLinkVerifyPinRequest::OAIGuestLinkVerifyPinRequest(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIGuestLinkVerifyPinRequest::~OAIGuestLinkVerifyPinRequest() = default;

void OAIGuestLinkVerifyPinRequest::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIGuestLinkVerifyPinRequestPrivate{});

        Q_D(OAIGuestLinkVerifyPinRequest);


        d->pin_isSet = false;
        d->pin_isValid = false;

        d->permission_id_isSet = false;
        d->permission_id_isValid = false;
    }
}

void OAIGuestLinkVerifyPinRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGuestLinkVerifyPinRequest::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIGuestLinkVerifyPinRequest);

    d->pin_isValid = ::OpenAPI::fromJsonValue(d->pin, json[QString("pin")]);
    d->pin_isSet = !json[QString("pin")].isNull() && d->pin_isValid;

    d->permission_id_isValid = ::OpenAPI::fromJsonValue(d->permission_id, json[QString("permissionId")]);
    d->permission_id_isSet = !json[QString("permissionId")].isNull() && d->permission_id_isValid;
}

QString OAIGuestLinkVerifyPinRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGuestLinkVerifyPinRequest::asJsonObject() const {
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->pin_isSet) {
        obj.insert(QString("pin"), ::OpenAPI::toJsonValue(d->pin));
    }
    if (d->permission_id_isSet) {
        obj.insert(QString("permissionId"), ::OpenAPI::toJsonValue(d->permission_id));
    }
    return obj;
}

QString OAIGuestLinkVerifyPinRequest::getPin() const {
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return {};
    }
    return d->pin;
}
void OAIGuestLinkVerifyPinRequest::setPin(const QString &pin) {
    Q_D(OAIGuestLinkVerifyPinRequest);
    Q_ASSERT(d);

    d->pin = pin;
    d->pin_isSet = true;
}

bool OAIGuestLinkVerifyPinRequest::is_pin_Set() const{
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return false;
    }

    return d->pin_isSet;
}

bool OAIGuestLinkVerifyPinRequest::is_pin_Valid() const{
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return false;
    }
    return d->pin_isValid;
}

QString OAIGuestLinkVerifyPinRequest::getPermissionId() const {
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return {};
    }
    return d->permission_id;
}
void OAIGuestLinkVerifyPinRequest::setPermissionId(const QString &permission_id) {
    Q_D(OAIGuestLinkVerifyPinRequest);
    Q_ASSERT(d);

    d->permission_id = permission_id;
    d->permission_id_isSet = true;
}

bool OAIGuestLinkVerifyPinRequest::is_permission_id_Set() const{
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return false;
    }

    return d->permission_id_isSet;
}

bool OAIGuestLinkVerifyPinRequest::is_permission_id_Valid() const{
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return false;
    }
    return d->permission_id_isValid;
}

bool OAIGuestLinkVerifyPinRequest::isSet() const {
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->pin_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->permission_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGuestLinkVerifyPinRequest::isValid() const {
    Q_D(const OAIGuestLinkVerifyPinRequest);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->pin_isValid && d->permission_id_isValid && true;
}

} // namespace OpenAPI
