// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIGuestLinkVerifyTokenRequest.h
 *
 * Request body for verifying a guest link token.
 */

#ifndef OAIGuestLinkVerifyTokenRequest_H
#define OAIGuestLinkVerifyTokenRequest_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIGuestLinkVerifyTokenRequestPrivate;

class OAIGuestLinkVerifyTokenRequest : public OAIObject {
public:
    OAIGuestLinkVerifyTokenRequest();
    OAIGuestLinkVerifyTokenRequest(const OAIGuestLinkVerifyTokenRequest &other);
    OAIGuestLinkVerifyTokenRequest(QString json);
    ~OAIGuestLinkVerifyTokenRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getToken() const;
    void setToken(const QString &token);
    bool is_token_Set() const;
    bool is_token_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIGuestLinkVerifyTokenRequest)
    QSharedPointer<OAIGuestLinkVerifyTokenRequestPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIGuestLinkVerifyTokenRequest)

#endif // OAIGuestLinkVerifyTokenRequest_H
