// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGuestLinkRedeemResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIGuestLinkRedeemResponsePrivate {
    friend class OAIGuestLinkRedeemResponse;

     QString permission_id;
     bool permission_id_isSet;
     bool permission_id_isValid;
};

OAIGuestLinkRedeemResponse::OAIGuestLinkRedeemResponse()
    : d_ptr()
{
}

OAIGuestLinkRedeemResponse::OAIGuestLinkRedeemResponse(const OAIGuestLinkRedeemResponse& other)
    : d_ptr(other.d_ptr)
{
}

OAIGuestLinkRedeemResponse::OAIGuestLinkRedeemResponse(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIGuestLinkRedeemResponse::~OAIGuestLinkRedeemResponse() = default;

void OAIGuestLinkRedeemResponse::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIGuestLinkRedeemResponsePrivate{});

        Q_D(OAIGuestLinkRedeemResponse);


        d->permission_id_isSet = false;
        d->permission_id_isValid = false;
    }
}

void OAIGuestLinkRedeemResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGuestLinkRedeemResponse::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIGuestLinkRedeemResponse);

    d->permission_id_isValid = ::OpenAPI::fromJsonValue(d->permission_id, json[QString("permissionId")]);
    d->permission_id_isSet = !json[QString("permissionId")].isNull() && d->permission_id_isValid;
}

QString OAIGuestLinkRedeemResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGuestLinkRedeemResponse::asJsonObject() const {
    Q_D(const OAIGuestLinkRedeemResponse);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->permission_id_isSet) {
        obj.insert(QString("permissionId"), ::OpenAPI::toJsonValue(d->permission_id));
    }
    return obj;
}

QString OAIGuestLinkRedeemResponse::getPermissionId() const {
    Q_D(const OAIGuestLinkRedeemResponse);
    if(!d){
        return {};
    }
    return d->permission_id;
}
void OAIGuestLinkRedeemResponse::setPermissionId(const QString &permission_id) {
    Q_D(OAIGuestLinkRedeemResponse);
    Q_ASSERT(d);

    d->permission_id = permission_id;
    d->permission_id_isSet = true;
}

bool OAIGuestLinkRedeemResponse::is_permission_id_Set() const{
    Q_D(const OAIGuestLinkRedeemResponse);
    if(!d){
        return false;
    }

    return d->permission_id_isSet;
}

bool OAIGuestLinkRedeemResponse::is_permission_id_Valid() const{
    Q_D(const OAIGuestLinkRedeemResponse);
    if(!d){
        return false;
    }
    return d->permission_id_isValid;
}

bool OAIGuestLinkRedeemResponse::isSet() const {
    Q_D(const OAIGuestLinkRedeemResponse);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->permission_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGuestLinkRedeemResponse::isValid() const {
    Q_D(const OAIGuestLinkRedeemResponse);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->permission_id_isValid && true;
}

} // namespace OpenAPI
