// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIGuestLinkRenewRequest.h
 *
 * Request body for renewing a guest link. Besides the share (permission) id, the previous guest link token or a (possibly expired) guest session cookie is required to authorize the renewal.
 */

#ifndef OAIGuestLinkRenewRequest_H
#define OAIGuestLinkRenewRequest_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIGuestLinkRenewRequestPrivate;

class OAIGuestLinkRenewRequest : public OAIObject {
public:
    OAIGuestLinkRenewRequest();
    OAIGuestLinkRenewRequest(const OAIGuestLinkRenewRequest &other);
    OAIGuestLinkRenewRequest(QString json);
    ~OAIGuestLinkRenewRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getPermissionId() const;
    void setPermissionId(const QString &permission_id);
    bool is_permission_id_Set() const;
    bool is_permission_id_Valid() const;

    QString getToken() const;
    void setToken(const QString &token);
    bool is_token_Set() const;
    bool is_token_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIGuestLinkRenewRequest)
    QSharedPointer<OAIGuestLinkRenewRequestPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIGuestLinkRenewRequest)

#endif // OAIGuestLinkRenewRequest_H
