// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGuestLinkRedeemRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIGuestLinkRedeemRequestPrivate {
    friend class OAIGuestLinkRedeemRequest;

     QString token;
     bool token_isSet;
     bool token_isValid;
};

OAIGuestLinkRedeemRequest::OAIGuestLinkRedeemRequest()
    : d_ptr()
{
}

OAIGuestLinkRedeemRequest::OAIGuestLinkRedeemRequest(const OAIGuestLinkRedeemRequest& other)
    : d_ptr(other.d_ptr)
{
}

OAIGuestLinkRedeemRequest::OAIGuestLinkRedeemRequest(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIGuestLinkRedeemRequest::~OAIGuestLinkRedeemRequest() = default;

void OAIGuestLinkRedeemRequest::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIGuestLinkRedeemRequestPrivate{});

        Q_D(OAIGuestLinkRedeemRequest);


        d->token_isSet = false;
        d->token_isValid = false;
    }
}

void OAIGuestLinkRedeemRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGuestLinkRedeemRequest::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIGuestLinkRedeemRequest);

    d->token_isValid = ::OpenAPI::fromJsonValue(d->token, json[QString("token")]);
    d->token_isSet = !json[QString("token")].isNull() && d->token_isValid;
}

QString OAIGuestLinkRedeemRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGuestLinkRedeemRequest::asJsonObject() const {
    Q_D(const OAIGuestLinkRedeemRequest);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->token_isSet) {
        obj.insert(QString("token"), ::OpenAPI::toJsonValue(d->token));
    }
    return obj;
}

QString OAIGuestLinkRedeemRequest::getToken() const {
    Q_D(const OAIGuestLinkRedeemRequest);
    if(!d){
        return {};
    }
    return d->token;
}
void OAIGuestLinkRedeemRequest::setToken(const QString &token) {
    Q_D(OAIGuestLinkRedeemRequest);
    Q_ASSERT(d);

    d->token = token;
    d->token_isSet = true;
}

bool OAIGuestLinkRedeemRequest::is_token_Set() const{
    Q_D(const OAIGuestLinkRedeemRequest);
    if(!d){
        return false;
    }

    return d->token_isSet;
}

bool OAIGuestLinkRedeemRequest::is_token_Valid() const{
    Q_D(const OAIGuestLinkRedeemRequest);
    if(!d){
        return false;
    }
    return d->token_isValid;
}

bool OAIGuestLinkRedeemRequest::isSet() const {
    Q_D(const OAIGuestLinkRedeemRequest);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->token_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGuestLinkRedeemRequest::isValid() const {
    Q_D(const OAIGuestLinkRedeemRequest);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->token_isValid && true;
}

} // namespace OpenAPI
