// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGuestLinkError.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIGuestLinkErrorPrivate {
    friend class OAIGuestLinkError;

     QString error_type;
     bool error_type_isSet;
     bool error_type_isValid;

     QString message;
     bool message_isSet;
     bool message_isValid;

     QString permission_id;
     bool permission_id_isSet;
     bool permission_id_isValid;
};

OAIGuestLinkError::OAIGuestLinkError()
    : d_ptr()
{
}

OAIGuestLinkError::OAIGuestLinkError(const OAIGuestLinkError& other)
    : d_ptr(other.d_ptr)
{
}

OAIGuestLinkError::OAIGuestLinkError(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIGuestLinkError::~OAIGuestLinkError() = default;

void OAIGuestLinkError::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIGuestLinkErrorPrivate{});

        Q_D(OAIGuestLinkError);


        d->error_type_isSet = false;
        d->error_type_isValid = false;

        d->message_isSet = false;
        d->message_isValid = false;

        d->permission_id_isSet = false;
        d->permission_id_isValid = false;
    }
}

void OAIGuestLinkError::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGuestLinkError::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIGuestLinkError);

    d->error_type_isValid = ::OpenAPI::fromJsonValue(d->error_type, json[QString("errorType")]);
    d->error_type_isSet = !json[QString("errorType")].isNull() && d->error_type_isValid;

    d->message_isValid = ::OpenAPI::fromJsonValue(d->message, json[QString("message")]);
    d->message_isSet = !json[QString("message")].isNull() && d->message_isValid;

    d->permission_id_isValid = ::OpenAPI::fromJsonValue(d->permission_id, json[QString("permissionId")]);
    d->permission_id_isSet = !json[QString("permissionId")].isNull() && d->permission_id_isValid;
}

QString OAIGuestLinkError::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGuestLinkError::asJsonObject() const {
    Q_D(const OAIGuestLinkError);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->error_type_isSet) {
        obj.insert(QString("errorType"), ::OpenAPI::toJsonValue(d->error_type));
    }
    if (d->message_isSet) {
        obj.insert(QString("message"), ::OpenAPI::toJsonValue(d->message));
    }
    if (d->permission_id_isSet) {
        obj.insert(QString("permissionId"), ::OpenAPI::toJsonValue(d->permission_id));
    }
    return obj;
}

QString OAIGuestLinkError::getErrorType() const {
    Q_D(const OAIGuestLinkError);
    if(!d){
        return {};
    }
    return d->error_type;
}
void OAIGuestLinkError::setErrorType(const QString &error_type) {
    Q_D(OAIGuestLinkError);
    Q_ASSERT(d);

    d->error_type = error_type;
    d->error_type_isSet = true;
}

bool OAIGuestLinkError::is_error_type_Set() const{
    Q_D(const OAIGuestLinkError);
    if(!d){
        return false;
    }

    return d->error_type_isSet;
}

bool OAIGuestLinkError::is_error_type_Valid() const{
    Q_D(const OAIGuestLinkError);
    if(!d){
        return false;
    }
    return d->error_type_isValid;
}

QString OAIGuestLinkError::getMessage() const {
    Q_D(const OAIGuestLinkError);
    if(!d){
        return {};
    }
    return d->message;
}
void OAIGuestLinkError::setMessage(const QString &message) {
    Q_D(OAIGuestLinkError);
    Q_ASSERT(d);

    d->message = message;
    d->message_isSet = true;
}

bool OAIGuestLinkError::is_message_Set() const{
    Q_D(const OAIGuestLinkError);
    if(!d){
        return false;
    }

    return d->message_isSet;
}

bool OAIGuestLinkError::is_message_Valid() const{
    Q_D(const OAIGuestLinkError);
    if(!d){
        return false;
    }
    return d->message_isValid;
}

QString OAIGuestLinkError::getPermissionId() const {
    Q_D(const OAIGuestLinkError);
    if(!d){
        return {};
    }
    return d->permission_id;
}
void OAIGuestLinkError::setPermissionId(const QString &permission_id) {
    Q_D(OAIGuestLinkError);
    Q_ASSERT(d);

    d->permission_id = permission_id;
    d->permission_id_isSet = true;
}

bool OAIGuestLinkError::is_permission_id_Set() const{
    Q_D(const OAIGuestLinkError);
    if(!d){
        return false;
    }

    return d->permission_id_isSet;
}

bool OAIGuestLinkError::is_permission_id_Valid() const{
    Q_D(const OAIGuestLinkError);
    if(!d){
        return false;
    }
    return d->permission_id_isValid;
}

bool OAIGuestLinkError::isSet() const {
    Q_D(const OAIGuestLinkError);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->error_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->message_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->permission_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGuestLinkError::isValid() const {
    Q_D(const OAIGuestLinkError);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->error_type_isValid && d->message_isValid && d->permission_id_isValid && true;
}

} // namespace OpenAPI
