// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIGuestLinkError.h
 *
 * Error returned by the guest link redeem endpoint.
 */

#ifndef OAIGuestLinkError_H
#define OAIGuestLinkError_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIGuestLinkErrorPrivate;

class OAIGuestLinkError : public OAIObject {
public:
    OAIGuestLinkError();
    OAIGuestLinkError(const OAIGuestLinkError &other);
    OAIGuestLinkError(QString json);
    ~OAIGuestLinkError() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getErrorType() const;
    void setErrorType(const QString &error_type);
    bool is_error_type_Set() const;
    bool is_error_type_Valid() const;

    QString getMessage() const;
    void setMessage(const QString &message);
    bool is_message_Set() const;
    bool is_message_Valid() const;

    QString getPermissionId() const;
    void setPermissionId(const QString &permission_id);
    bool is_permission_id_Set() const;
    bool is_permission_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIGuestLinkError)
    QSharedPointer<OAIGuestLinkErrorPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIGuestLinkError)

#endif // OAIGuestLinkError_H
