// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIGuestLinkRenewRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIGuestLinkRenewRequestPrivate {
    friend class OAIGuestLinkRenewRequest;

     QString permission_id;
     bool permission_id_isSet;
     bool permission_id_isValid;

     QString token;
     bool token_isSet;
     bool token_isValid;
};

OAIGuestLinkRenewRequest::OAIGuestLinkRenewRequest()
    : d_ptr()
{
}

OAIGuestLinkRenewRequest::OAIGuestLinkRenewRequest(const OAIGuestLinkRenewRequest& other)
    : d_ptr(other.d_ptr)
{
}

OAIGuestLinkRenewRequest::OAIGuestLinkRenewRequest(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIGuestLinkRenewRequest::~OAIGuestLinkRenewRequest() = default;

void OAIGuestLinkRenewRequest::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIGuestLinkRenewRequestPrivate{});

        Q_D(OAIGuestLinkRenewRequest);


        d->permission_id_isSet = false;
        d->permission_id_isValid = false;

        d->token_isSet = false;
        d->token_isValid = false;
    }
}

void OAIGuestLinkRenewRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIGuestLinkRenewRequest::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIGuestLinkRenewRequest);

    d->permission_id_isValid = ::OpenAPI::fromJsonValue(d->permission_id, json[QString("permissionId")]);
    d->permission_id_isSet = !json[QString("permissionId")].isNull() && d->permission_id_isValid;

    d->token_isValid = ::OpenAPI::fromJsonValue(d->token, json[QString("token")]);
    d->token_isSet = !json[QString("token")].isNull() && d->token_isValid;
}

QString OAIGuestLinkRenewRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIGuestLinkRenewRequest::asJsonObject() const {
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->permission_id_isSet) {
        obj.insert(QString("permissionId"), ::OpenAPI::toJsonValue(d->permission_id));
    }
    if (d->token_isSet) {
        obj.insert(QString("token"), ::OpenAPI::toJsonValue(d->token));
    }
    return obj;
}

QString OAIGuestLinkRenewRequest::getPermissionId() const {
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return {};
    }
    return d->permission_id;
}
void OAIGuestLinkRenewRequest::setPermissionId(const QString &permission_id) {
    Q_D(OAIGuestLinkRenewRequest);
    Q_ASSERT(d);

    d->permission_id = permission_id;
    d->permission_id_isSet = true;
}

bool OAIGuestLinkRenewRequest::is_permission_id_Set() const{
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return false;
    }

    return d->permission_id_isSet;
}

bool OAIGuestLinkRenewRequest::is_permission_id_Valid() const{
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return false;
    }
    return d->permission_id_isValid;
}

QString OAIGuestLinkRenewRequest::getToken() const {
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return {};
    }
    return d->token;
}
void OAIGuestLinkRenewRequest::setToken(const QString &token) {
    Q_D(OAIGuestLinkRenewRequest);
    Q_ASSERT(d);

    d->token = token;
    d->token_isSet = true;
}

bool OAIGuestLinkRenewRequest::is_token_Set() const{
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return false;
    }

    return d->token_isSet;
}

bool OAIGuestLinkRenewRequest::is_token_Valid() const{
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return false;
    }
    return d->token_isValid;
}

bool OAIGuestLinkRenewRequest::isSet() const {
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->permission_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->token_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIGuestLinkRenewRequest::isValid() const {
    Q_D(const OAIGuestLinkRenewRequest);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->permission_id_isValid && true;
}

} // namespace OpenAPI
