// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIInvitedUserMessageInfo.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIInvitedUserMessageInfoPrivate {
    friend class OAIInvitedUserMessageInfo;

     QList<OAIRecipient> cc_recipients;
     bool cc_recipients_isSet;
     bool cc_recipients_isValid;

     QString customized_message_body;
     bool customized_message_body_isSet;
     bool customized_message_body_isValid;

     QString message_language;
     bool message_language_isSet;
     bool message_language_isValid;
};

OAIInvitedUserMessageInfo::OAIInvitedUserMessageInfo()
    : d_ptr()
{
}

OAIInvitedUserMessageInfo::OAIInvitedUserMessageInfo(const OAIInvitedUserMessageInfo& other)
    : d_ptr(other.d_ptr)
{
}

OAIInvitedUserMessageInfo::OAIInvitedUserMessageInfo(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIInvitedUserMessageInfo::~OAIInvitedUserMessageInfo() = default;

void OAIInvitedUserMessageInfo::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIInvitedUserMessageInfoPrivate{});

        Q_D(OAIInvitedUserMessageInfo);


        d->cc_recipients_isSet = false;
        d->cc_recipients_isValid = false;

        d->customized_message_body_isSet = false;
        d->customized_message_body_isValid = false;

        d->message_language_isSet = false;
        d->message_language_isValid = false;
    }
}

void OAIInvitedUserMessageInfo::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIInvitedUserMessageInfo::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIInvitedUserMessageInfo);

    d->cc_recipients_isValid = ::OpenAPI::fromJsonValue(d->cc_recipients, json[QString("ccRecipients")]);
    d->cc_recipients_isSet = !json[QString("ccRecipients")].isNull() && d->cc_recipients_isValid;

    d->customized_message_body_isValid = ::OpenAPI::fromJsonValue(d->customized_message_body, json[QString("customizedMessageBody")]);
    d->customized_message_body_isSet = !json[QString("customizedMessageBody")].isNull() && d->customized_message_body_isValid;

    d->message_language_isValid = ::OpenAPI::fromJsonValue(d->message_language, json[QString("messageLanguage")]);
    d->message_language_isSet = !json[QString("messageLanguage")].isNull() && d->message_language_isValid;
}

QString OAIInvitedUserMessageInfo::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIInvitedUserMessageInfo::asJsonObject() const {
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->cc_recipients.size() > 0) {
        obj.insert(QString("ccRecipients"), ::OpenAPI::toJsonValue(d->cc_recipients));
    }
    if (d->customized_message_body_isSet) {
        obj.insert(QString("customizedMessageBody"), ::OpenAPI::toJsonValue(d->customized_message_body));
    }
    if (d->message_language_isSet) {
        obj.insert(QString("messageLanguage"), ::OpenAPI::toJsonValue(d->message_language));
    }
    return obj;
}

QList<OAIRecipient> OAIInvitedUserMessageInfo::getCcRecipients() const {
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return {};
    }
    return d->cc_recipients;
}
void OAIInvitedUserMessageInfo::setCcRecipients(const QList<OAIRecipient> &cc_recipients) {
    Q_D(OAIInvitedUserMessageInfo);
    Q_ASSERT(d);

    d->cc_recipients = cc_recipients;
    d->cc_recipients_isSet = true;
}

bool OAIInvitedUserMessageInfo::is_cc_recipients_Set() const{
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return false;
    }

    return d->cc_recipients_isSet;
}

bool OAIInvitedUserMessageInfo::is_cc_recipients_Valid() const{
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return false;
    }
    return d->cc_recipients_isValid;
}

QString OAIInvitedUserMessageInfo::getCustomizedMessageBody() const {
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return {};
    }
    return d->customized_message_body;
}
void OAIInvitedUserMessageInfo::setCustomizedMessageBody(const QString &customized_message_body) {
    Q_D(OAIInvitedUserMessageInfo);
    Q_ASSERT(d);

    d->customized_message_body = customized_message_body;
    d->customized_message_body_isSet = true;
}

bool OAIInvitedUserMessageInfo::is_customized_message_body_Set() const{
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return false;
    }

    return d->customized_message_body_isSet;
}

bool OAIInvitedUserMessageInfo::is_customized_message_body_Valid() const{
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return false;
    }
    return d->customized_message_body_isValid;
}

QString OAIInvitedUserMessageInfo::getMessageLanguage() const {
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return {};
    }
    return d->message_language;
}
void OAIInvitedUserMessageInfo::setMessageLanguage(const QString &message_language) {
    Q_D(OAIInvitedUserMessageInfo);
    Q_ASSERT(d);

    d->message_language = message_language;
    d->message_language_isSet = true;
}

bool OAIInvitedUserMessageInfo::is_message_language_Set() const{
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return false;
    }

    return d->message_language_isSet;
}

bool OAIInvitedUserMessageInfo::is_message_language_Valid() const{
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return false;
    }
    return d->message_language_isValid;
}

bool OAIInvitedUserMessageInfo::isSet() const {
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->cc_recipients.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->customized_message_body_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->message_language_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIInvitedUserMessageInfo::isValid() const {
    Q_D(const OAIInvitedUserMessageInfo);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
