// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInvitedUserMessageInfo.h
 *
 * Additional information about the invitation message.
 */

#ifndef OAIInvitedUserMessageInfo_H
#define OAIInvitedUserMessageInfo_H

#include <QJsonObject>

#include "OAIRecipient.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIRecipient;


class OAIInvitedUserMessageInfoPrivate;

class OAIInvitedUserMessageInfo : public OAIObject {
public:
    OAIInvitedUserMessageInfo();
    OAIInvitedUserMessageInfo(const OAIInvitedUserMessageInfo &other);
    OAIInvitedUserMessageInfo(QString json);
    ~OAIInvitedUserMessageInfo() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIRecipient> getCcRecipients() const;
    void setCcRecipients(const QList<OAIRecipient> &cc_recipients);
    bool is_cc_recipients_Set() const;
    bool is_cc_recipients_Valid() const;

    QString getCustomizedMessageBody() const;
    void setCustomizedMessageBody(const QString &customized_message_body);
    bool is_customized_message_body_Set() const;
    bool is_customized_message_body_Valid() const;

    QString getMessageLanguage() const;
    void setMessageLanguage(const QString &message_language);
    bool is_message_language_Set() const;
    bool is_message_language_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIInvitedUserMessageInfo)
    QSharedPointer<OAIInvitedUserMessageInfoPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIInvitedUserMessageInfo)

#endif // OAIInvitedUserMessageInfo_H
