// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInvitation.h
 *
 * Represents an invitation to a drive item. 
 */

#ifndef OAIInvitation_H
#define OAIInvitation_H

#include <QJsonObject>

#include "OAIInvitedUserMessageInfo.h"
#include "OAIUser.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIInvitedUserMessageInfo;
class OAIUser;


class OAIInvitationPrivate;

class OAIInvitation : public OAIObject {
public:
    OAIInvitation();
    OAIInvitation(const OAIInvitation &other);
    OAIInvitation(QString json);
    ~OAIInvitation() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getInvitedUserDisplayName() const;
    void setInvitedUserDisplayName(const QString &invited_user_display_name);
    bool is_invited_user_display_name_Set() const;
    bool is_invited_user_display_name_Valid() const;

    QString getInvitedUserEmailAddress() const;
    void setInvitedUserEmailAddress(const QString &invited_user_email_address);
    bool is_invited_user_email_address_Set() const;
    bool is_invited_user_email_address_Valid() const;

    OAIInvitedUserMessageInfo getInvitedUserMessageInfo() const;
    void setInvitedUserMessageInfo(const OAIInvitedUserMessageInfo &invited_user_message_info);
    bool is_invited_user_message_info_Set() const;
    bool is_invited_user_message_info_Valid() const;

    bool isSendInvitationMessage() const;
    void setSendInvitationMessage(const bool &send_invitation_message);
    bool is_send_invitation_message_Set() const;
    bool is_send_invitation_message_Valid() const;

    QString getInviteRedirectUrl() const;
    void setInviteRedirectUrl(const QString &invite_redirect_url);
    bool is_invite_redirect_url_Set() const;
    bool is_invite_redirect_url_Valid() const;

    QString getInviteRedeemUrl() const;
    void setInviteRedeemUrl(const QString &invite_redeem_url);
    bool is_invite_redeem_url_Set() const;
    bool is_invite_redeem_url_Valid() const;

    QString getStatus() const;
    void setStatus(const QString &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    OAIUser getInvitedUser() const;
    void setInvitedUser(const OAIUser &invited_user);
    bool is_invited_user_Set() const;
    bool is_invited_user_Valid() const;

    QString getInvitedUserType() const;
    void setInvitedUserType(const QString &invited_user_type);
    bool is_invited_user_type_Set() const;
    bool is_invited_user_type_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIInvitation)
    QSharedPointer<OAIInvitationPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIInvitation)

#endif // OAIInvitation_H
