// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIInvitation.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIInvitationPrivate {
    friend class OAIInvitation;

     QString invited_user_display_name;
     bool invited_user_display_name_isSet;
     bool invited_user_display_name_isValid;

     QString invited_user_email_address;
     bool invited_user_email_address_isSet;
     bool invited_user_email_address_isValid;

     OAIInvitedUserMessageInfo invited_user_message_info;
     bool invited_user_message_info_isSet;
     bool invited_user_message_info_isValid;

     bool send_invitation_message;
     bool send_invitation_message_isSet;
     bool send_invitation_message_isValid;

     QString invite_redirect_url;
     bool invite_redirect_url_isSet;
     bool invite_redirect_url_isValid;

     QString invite_redeem_url;
     bool invite_redeem_url_isSet;
     bool invite_redeem_url_isValid;

     QString status;
     bool status_isSet;
     bool status_isValid;

     OAIUser invited_user;
     bool invited_user_isSet;
     bool invited_user_isValid;

     QString invited_user_type;
     bool invited_user_type_isSet;
     bool invited_user_type_isValid;
};

OAIInvitation::OAIInvitation()
    : d_ptr()
{
}

OAIInvitation::OAIInvitation(const OAIInvitation& other)
    : d_ptr(other.d_ptr)
{
}

OAIInvitation::OAIInvitation(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIInvitation::~OAIInvitation() = default;

void OAIInvitation::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIInvitationPrivate{});

        Q_D(OAIInvitation);


        d->invited_user_display_name_isSet = false;
        d->invited_user_display_name_isValid = false;

        d->invited_user_email_address_isSet = false;
        d->invited_user_email_address_isValid = false;

        d->invited_user_message_info_isSet = false;
        d->invited_user_message_info_isValid = false;

        d->send_invitation_message_isSet = false;
        d->send_invitation_message_isValid = false;

        d->invite_redirect_url_isSet = false;
        d->invite_redirect_url_isValid = false;

        d->invite_redeem_url_isSet = false;
        d->invite_redeem_url_isValid = false;

        d->status_isSet = false;
        d->status_isValid = false;

        d->invited_user_isSet = false;
        d->invited_user_isValid = false;

        d->invited_user_type_isSet = false;
        d->invited_user_type_isValid = false;
    }
}

void OAIInvitation::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIInvitation::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIInvitation);

    d->invited_user_display_name_isValid = ::OpenAPI::fromJsonValue(d->invited_user_display_name, json[QString("invitedUserDisplayName")]);
    d->invited_user_display_name_isSet = !json[QString("invitedUserDisplayName")].isNull() && d->invited_user_display_name_isValid;

    d->invited_user_email_address_isValid = ::OpenAPI::fromJsonValue(d->invited_user_email_address, json[QString("invitedUserEmailAddress")]);
    d->invited_user_email_address_isSet = !json[QString("invitedUserEmailAddress")].isNull() && d->invited_user_email_address_isValid;

    d->invited_user_message_info_isValid = ::OpenAPI::fromJsonValue(d->invited_user_message_info, json[QString("invitedUserMessageInfo")]);
    d->invited_user_message_info_isSet = !json[QString("invitedUserMessageInfo")].isNull() && d->invited_user_message_info_isValid;

    d->send_invitation_message_isValid = ::OpenAPI::fromJsonValue(d->send_invitation_message, json[QString("sendInvitationMessage")]);
    d->send_invitation_message_isSet = !json[QString("sendInvitationMessage")].isNull() && d->send_invitation_message_isValid;

    d->invite_redirect_url_isValid = ::OpenAPI::fromJsonValue(d->invite_redirect_url, json[QString("inviteRedirectUrl")]);
    d->invite_redirect_url_isSet = !json[QString("inviteRedirectUrl")].isNull() && d->invite_redirect_url_isValid;

    d->invite_redeem_url_isValid = ::OpenAPI::fromJsonValue(d->invite_redeem_url, json[QString("inviteRedeemUrl")]);
    d->invite_redeem_url_isSet = !json[QString("inviteRedeemUrl")].isNull() && d->invite_redeem_url_isValid;

    d->status_isValid = ::OpenAPI::fromJsonValue(d->status, json[QString("status")]);
    d->status_isSet = !json[QString("status")].isNull() && d->status_isValid;

    d->invited_user_isValid = ::OpenAPI::fromJsonValue(d->invited_user, json[QString("invitedUser")]);
    d->invited_user_isSet = !json[QString("invitedUser")].isNull() && d->invited_user_isValid;

    d->invited_user_type_isValid = ::OpenAPI::fromJsonValue(d->invited_user_type, json[QString("invitedUserType")]);
    d->invited_user_type_isSet = !json[QString("invitedUserType")].isNull() && d->invited_user_type_isValid;
}

QString OAIInvitation::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIInvitation::asJsonObject() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->invited_user_display_name_isSet) {
        obj.insert(QString("invitedUserDisplayName"), ::OpenAPI::toJsonValue(d->invited_user_display_name));
    }
    if (d->invited_user_email_address_isSet) {
        obj.insert(QString("invitedUserEmailAddress"), ::OpenAPI::toJsonValue(d->invited_user_email_address));
    }
    if (d->invited_user_message_info.isSet()) {
        obj.insert(QString("invitedUserMessageInfo"), ::OpenAPI::toJsonValue(d->invited_user_message_info));
    }
    if (d->send_invitation_message_isSet) {
        obj.insert(QString("sendInvitationMessage"), ::OpenAPI::toJsonValue(d->send_invitation_message));
    }
    if (d->invite_redirect_url_isSet) {
        obj.insert(QString("inviteRedirectUrl"), ::OpenAPI::toJsonValue(d->invite_redirect_url));
    }
    if (d->invite_redeem_url_isSet) {
        obj.insert(QString("inviteRedeemUrl"), ::OpenAPI::toJsonValue(d->invite_redeem_url));
    }
    if (d->status_isSet) {
        obj.insert(QString("status"), ::OpenAPI::toJsonValue(d->status));
    }
    if (d->invited_user.isSet()) {
        obj.insert(QString("invitedUser"), ::OpenAPI::toJsonValue(d->invited_user));
    }
    if (d->invited_user_type_isSet) {
        obj.insert(QString("invitedUserType"), ::OpenAPI::toJsonValue(d->invited_user_type));
    }
    return obj;
}

QString OAIInvitation::getInvitedUserDisplayName() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->invited_user_display_name;
}
void OAIInvitation::setInvitedUserDisplayName(const QString &invited_user_display_name) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->invited_user_display_name = invited_user_display_name;
    d->invited_user_display_name_isSet = true;
}

bool OAIInvitation::is_invited_user_display_name_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->invited_user_display_name_isSet;
}

bool OAIInvitation::is_invited_user_display_name_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->invited_user_display_name_isValid;
}

QString OAIInvitation::getInvitedUserEmailAddress() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->invited_user_email_address;
}
void OAIInvitation::setInvitedUserEmailAddress(const QString &invited_user_email_address) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->invited_user_email_address = invited_user_email_address;
    d->invited_user_email_address_isSet = true;
}

bool OAIInvitation::is_invited_user_email_address_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->invited_user_email_address_isSet;
}

bool OAIInvitation::is_invited_user_email_address_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->invited_user_email_address_isValid;
}

OAIInvitedUserMessageInfo OAIInvitation::getInvitedUserMessageInfo() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->invited_user_message_info;
}
void OAIInvitation::setInvitedUserMessageInfo(const OAIInvitedUserMessageInfo &invited_user_message_info) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->invited_user_message_info = invited_user_message_info;
    d->invited_user_message_info_isSet = true;
}

bool OAIInvitation::is_invited_user_message_info_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->invited_user_message_info_isSet;
}

bool OAIInvitation::is_invited_user_message_info_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->invited_user_message_info_isValid;
}

bool OAIInvitation::isSendInvitationMessage() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->send_invitation_message;
}
void OAIInvitation::setSendInvitationMessage(const bool &send_invitation_message) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->send_invitation_message = send_invitation_message;
    d->send_invitation_message_isSet = true;
}

bool OAIInvitation::is_send_invitation_message_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->send_invitation_message_isSet;
}

bool OAIInvitation::is_send_invitation_message_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->send_invitation_message_isValid;
}

QString OAIInvitation::getInviteRedirectUrl() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->invite_redirect_url;
}
void OAIInvitation::setInviteRedirectUrl(const QString &invite_redirect_url) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->invite_redirect_url = invite_redirect_url;
    d->invite_redirect_url_isSet = true;
}

bool OAIInvitation::is_invite_redirect_url_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->invite_redirect_url_isSet;
}

bool OAIInvitation::is_invite_redirect_url_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->invite_redirect_url_isValid;
}

QString OAIInvitation::getInviteRedeemUrl() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->invite_redeem_url;
}
void OAIInvitation::setInviteRedeemUrl(const QString &invite_redeem_url) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->invite_redeem_url = invite_redeem_url;
    d->invite_redeem_url_isSet = true;
}

bool OAIInvitation::is_invite_redeem_url_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->invite_redeem_url_isSet;
}

bool OAIInvitation::is_invite_redeem_url_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->invite_redeem_url_isValid;
}

QString OAIInvitation::getStatus() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->status;
}
void OAIInvitation::setStatus(const QString &status) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->status = status;
    d->status_isSet = true;
}

bool OAIInvitation::is_status_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->status_isSet;
}

bool OAIInvitation::is_status_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->status_isValid;
}

OAIUser OAIInvitation::getInvitedUser() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->invited_user;
}
void OAIInvitation::setInvitedUser(const OAIUser &invited_user) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->invited_user = invited_user;
    d->invited_user_isSet = true;
}

bool OAIInvitation::is_invited_user_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->invited_user_isSet;
}

bool OAIInvitation::is_invited_user_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->invited_user_isValid;
}

QString OAIInvitation::getInvitedUserType() const {
    Q_D(const OAIInvitation);
    if(!d){
        return {};
    }
    return d->invited_user_type;
}
void OAIInvitation::setInvitedUserType(const QString &invited_user_type) {
    Q_D(OAIInvitation);
    Q_ASSERT(d);

    d->invited_user_type = invited_user_type;
    d->invited_user_type_isSet = true;
}

bool OAIInvitation::is_invited_user_type_Set() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }

    return d->invited_user_type_isSet;
}

bool OAIInvitation::is_invited_user_type_Valid() const{
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    return d->invited_user_type_isValid;
}

bool OAIInvitation::isSet() const {
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->invited_user_display_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->invited_user_email_address_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->invited_user_message_info.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (d->send_invitation_message_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->invite_redirect_url_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->invite_redeem_url_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->status_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->invited_user.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (d->invited_user_type_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIInvitation::isValid() const {
    Q_D(const OAIInvitation);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
