// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAILockInfo.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAILockInfoPrivate {
    friend class OAILockInfo;

     QString lock_type;
     bool lock_type_isSet;
     bool lock_type_isValid;

     QDateTime created_date_time;
     bool created_date_time_isSet;
     bool created_date_time_isValid;

     QDateTime expiration_date_time;
     bool expiration_date_time_isSet;
     bool expiration_date_time_isValid;

     QList<OAIIdentity> owners;
     bool owners_isSet;
     bool owners_isValid;

     QString libre_graph_app_name;
     bool libre_graph_app_name_isSet;
     bool libre_graph_app_name_isValid;
};

OAILockInfo::OAILockInfo()
    : d_ptr()
{
}

OAILockInfo::OAILockInfo(const OAILockInfo& other)
    : d_ptr(other.d_ptr)
{
}

OAILockInfo::OAILockInfo(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAILockInfo::~OAILockInfo() = default;

void OAILockInfo::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAILockInfoPrivate{});

        Q_D(OAILockInfo);


        d->lock_type_isSet = false;
        d->lock_type_isValid = false;

        d->created_date_time_isSet = false;
        d->created_date_time_isValid = false;

        d->expiration_date_time_isSet = false;
        d->expiration_date_time_isValid = false;

        d->owners_isSet = false;
        d->owners_isValid = false;

        d->libre_graph_app_name_isSet = false;
        d->libre_graph_app_name_isValid = false;
    }
}

void OAILockInfo::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAILockInfo::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAILockInfo);

    d->lock_type_isValid = ::OpenAPI::fromJsonValue(d->lock_type, json[QString("lockType")]);
    d->lock_type_isSet = !json[QString("lockType")].isNull() && d->lock_type_isValid;

    d->created_date_time_isValid = ::OpenAPI::fromJsonValue(d->created_date_time, json[QString("createdDateTime")]);
    d->created_date_time_isSet = !json[QString("createdDateTime")].isNull() && d->created_date_time_isValid;

    d->expiration_date_time_isValid = ::OpenAPI::fromJsonValue(d->expiration_date_time, json[QString("expirationDateTime")]);
    d->expiration_date_time_isSet = !json[QString("expirationDateTime")].isNull() && d->expiration_date_time_isValid;

    d->owners_isValid = ::OpenAPI::fromJsonValue(d->owners, json[QString("owners")]);
    d->owners_isSet = !json[QString("owners")].isNull() && d->owners_isValid;

    d->libre_graph_app_name_isValid = ::OpenAPI::fromJsonValue(d->libre_graph_app_name, json[QString("@libre.graph.appName")]);
    d->libre_graph_app_name_isSet = !json[QString("@libre.graph.appName")].isNull() && d->libre_graph_app_name_isValid;
}

QString OAILockInfo::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAILockInfo::asJsonObject() const {
    Q_D(const OAILockInfo);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->lock_type_isSet) {
        obj.insert(QString("lockType"), ::OpenAPI::toJsonValue(d->lock_type));
    }
    if (d->created_date_time_isSet) {
        obj.insert(QString("createdDateTime"), ::OpenAPI::toJsonValue(d->created_date_time));
    }
    if (d->expiration_date_time_isSet) {
        obj.insert(QString("expirationDateTime"), ::OpenAPI::toJsonValue(d->expiration_date_time));
    }
    if (d->owners.size() > 0) {
        obj.insert(QString("owners"), ::OpenAPI::toJsonValue(d->owners));
    }
    if (d->libre_graph_app_name_isSet) {
        obj.insert(QString("@libre.graph.appName"), ::OpenAPI::toJsonValue(d->libre_graph_app_name));
    }
    return obj;
}

QString OAILockInfo::getLockType() const {
    Q_D(const OAILockInfo);
    if(!d){
        return {};
    }
    return d->lock_type;
}
void OAILockInfo::setLockType(const QString &lock_type) {
    Q_D(OAILockInfo);
    Q_ASSERT(d);

    d->lock_type = lock_type;
    d->lock_type_isSet = true;
}

bool OAILockInfo::is_lock_type_Set() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }

    return d->lock_type_isSet;
}

bool OAILockInfo::is_lock_type_Valid() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }
    return d->lock_type_isValid;
}

QDateTime OAILockInfo::getCreatedDateTime() const {
    Q_D(const OAILockInfo);
    if(!d){
        return {};
    }
    return d->created_date_time;
}
void OAILockInfo::setCreatedDateTime(const QDateTime &created_date_time) {
    Q_D(OAILockInfo);
    Q_ASSERT(d);

    d->created_date_time = created_date_time;
    d->created_date_time_isSet = true;
}

bool OAILockInfo::is_created_date_time_Set() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }

    return d->created_date_time_isSet;
}

bool OAILockInfo::is_created_date_time_Valid() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }
    return d->created_date_time_isValid;
}

QDateTime OAILockInfo::getExpirationDateTime() const {
    Q_D(const OAILockInfo);
    if(!d){
        return {};
    }
    return d->expiration_date_time;
}
void OAILockInfo::setExpirationDateTime(const QDateTime &expiration_date_time) {
    Q_D(OAILockInfo);
    Q_ASSERT(d);

    d->expiration_date_time = expiration_date_time;
    d->expiration_date_time_isSet = true;
}

bool OAILockInfo::is_expiration_date_time_Set() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }

    return d->expiration_date_time_isSet;
}

bool OAILockInfo::is_expiration_date_time_Valid() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }
    return d->expiration_date_time_isValid;
}

QList<OAIIdentity> OAILockInfo::getOwners() const {
    Q_D(const OAILockInfo);
    if(!d){
        return {};
    }
    return d->owners;
}
void OAILockInfo::setOwners(const QList<OAIIdentity> &owners) {
    Q_D(OAILockInfo);
    Q_ASSERT(d);

    d->owners = owners;
    d->owners_isSet = true;
}

bool OAILockInfo::is_owners_Set() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }

    return d->owners_isSet;
}

bool OAILockInfo::is_owners_Valid() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }
    return d->owners_isValid;
}

QString OAILockInfo::getLibreGraphAppName() const {
    Q_D(const OAILockInfo);
    if(!d){
        return {};
    }
    return d->libre_graph_app_name;
}
void OAILockInfo::setLibreGraphAppName(const QString &libre_graph_app_name) {
    Q_D(OAILockInfo);
    Q_ASSERT(d);

    d->libre_graph_app_name = libre_graph_app_name;
    d->libre_graph_app_name_isSet = true;
}

bool OAILockInfo::is_libre_graph_app_name_Set() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }

    return d->libre_graph_app_name_isSet;
}

bool OAILockInfo::is_libre_graph_app_name_Valid() const{
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }
    return d->libre_graph_app_name_isValid;
}

bool OAILockInfo::isSet() const {
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->lock_type_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->created_date_time_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->expiration_date_time_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->owners.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->libre_graph_app_name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAILockInfo::isValid() const {
    Q_D(const OAILockInfo);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
