// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILockInfo.h
 *
 * Read-only lock metadata for a file, matching the MS Graph beta lockInfo resource. Indicates whether the file is locked, the kind of lock, when it was created, when it expires and who holds it. 
 */

#ifndef OAILockInfo_H
#define OAILockInfo_H

#include <QJsonObject>

#include "OAIIdentity.h"
#include <QDateTime>
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIIdentity;


class OAILockInfoPrivate;

class OAILockInfo : public OAIObject {
public:
    OAILockInfo();
    OAILockInfo(const OAILockInfo &other);
    OAILockInfo(QString json);
    ~OAILockInfo() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getLockType() const;
    void setLockType(const QString &lock_type);
    bool is_lock_type_Set() const;
    bool is_lock_type_Valid() const;

    QDateTime getCreatedDateTime() const;
    void setCreatedDateTime(const QDateTime &created_date_time);
    bool is_created_date_time_Set() const;
    bool is_created_date_time_Valid() const;

    QDateTime getExpirationDateTime() const;
    void setExpirationDateTime(const QDateTime &expiration_date_time);
    bool is_expiration_date_time_Set() const;
    bool is_expiration_date_time_Valid() const;

    QList<OAIIdentity> getOwners() const;
    void setOwners(const QList<OAIIdentity> &owners);
    bool is_owners_Set() const;
    bool is_owners_Valid() const;

    QString getLibreGraphAppName() const;
    void setLibreGraphAppName(const QString &libre_graph_app_name);
    bool is_libre_graph_app_name_Set() const;
    bool is_libre_graph_app_name_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAILockInfo)
    QSharedPointer<OAILockInfoPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAILockInfo)

#endif // OAILockInfo_H
