// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILivePhoto.h
 *
 * Apple Live Photo metadata. A Live Photo is a pair of files sharing one content identifier: a still image (HEIC or JPEG) and a short QuickTime video. Unlike a Motion Photo, the two parts are separate driveItems. The presence of this facet indicates the item was captured as part of a Live Photo; the counterpart is the driveItem whose livePhoto facet carries the same contentId. Whether an item is the still image or the video half follows from its photo/video facets and MIME type.  There is no public file format specification; the metadata keys are documented as AVFoundation metadata identifiers: https://developer.apple.com/documentation/avfoundation/avmetadataidentifier On the still image they are stored in the Apple maker note, on the video as com.apple.quicktime.* QuickTime metadata keys. 
 */

#ifndef OAILivePhoto_H
#define OAILivePhoto_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAILivePhotoPrivate;

class OAILivePhoto : public OAIObject {
public:
    OAILivePhoto();
    OAILivePhoto(const OAILivePhoto &other);
    OAILivePhoto(QString json);
    ~OAILivePhoto() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getContentId() const;
    void setContentId(const QString &content_id);
    bool is_content_id_Set() const;
    bool is_content_id_Valid() const;

    qint64 getStillImageTimeUs() const;
    void setStillImageTimeUs(const qint64 &still_image_time_us);
    bool is_still_image_time_us_Set() const;
    bool is_still_image_time_us_Valid() const;

    bool isRAuto() const;
    void setRAuto(const bool &r_auto);
    bool is_r_auto_Set() const;
    bool is_r_auto_Valid() const;

    double getVitalityScore() const;
    void setVitalityScore(const double &vitality_score);
    bool is_vitality_score_Set() const;
    bool is_vitality_score_Valid() const;

    qint64 getVitalityScoringVersion() const;
    void setVitalityScoringVersion(const qint64 &vitality_scoring_version);
    bool is_vitality_scoring_version_Set() const;
    bool is_vitality_scoring_version_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAILivePhoto)
    QSharedPointer<OAILivePhotoPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAILivePhoto)

#endif // OAILivePhoto_H
