// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAILivePhoto.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAILivePhotoPrivate {
    friend class OAILivePhoto;

     QString content_id;
     bool content_id_isSet;
     bool content_id_isValid;

     qint64 still_image_time_us;
     bool still_image_time_us_isSet;
     bool still_image_time_us_isValid;

     bool r_auto;
     bool r_auto_isSet;
     bool r_auto_isValid;

     double vitality_score;
     bool vitality_score_isSet;
     bool vitality_score_isValid;

     qint64 vitality_scoring_version;
     bool vitality_scoring_version_isSet;
     bool vitality_scoring_version_isValid;
};

OAILivePhoto::OAILivePhoto()
    : d_ptr()
{
}

OAILivePhoto::OAILivePhoto(const OAILivePhoto& other)
    : d_ptr(other.d_ptr)
{
}

OAILivePhoto::OAILivePhoto(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAILivePhoto::~OAILivePhoto() = default;

void OAILivePhoto::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAILivePhotoPrivate{});

        Q_D(OAILivePhoto);


        d->content_id_isSet = false;
        d->content_id_isValid = false;

        d->still_image_time_us_isSet = false;
        d->still_image_time_us_isValid = false;

        d->r_auto_isSet = false;
        d->r_auto_isValid = false;

        d->vitality_score_isSet = false;
        d->vitality_score_isValid = false;

        d->vitality_scoring_version_isSet = false;
        d->vitality_scoring_version_isValid = false;
    }
}

void OAILivePhoto::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAILivePhoto::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAILivePhoto);

    d->content_id_isValid = ::OpenAPI::fromJsonValue(d->content_id, json[QString("contentId")]);
    d->content_id_isSet = !json[QString("contentId")].isNull() && d->content_id_isValid;

    d->still_image_time_us_isValid = ::OpenAPI::fromJsonValue(d->still_image_time_us, json[QString("stillImageTimeUs")]);
    d->still_image_time_us_isSet = !json[QString("stillImageTimeUs")].isNull() && d->still_image_time_us_isValid;

    d->r_auto_isValid = ::OpenAPI::fromJsonValue(d->r_auto, json[QString("auto")]);
    d->r_auto_isSet = !json[QString("auto")].isNull() && d->r_auto_isValid;

    d->vitality_score_isValid = ::OpenAPI::fromJsonValue(d->vitality_score, json[QString("vitalityScore")]);
    d->vitality_score_isSet = !json[QString("vitalityScore")].isNull() && d->vitality_score_isValid;

    d->vitality_scoring_version_isValid = ::OpenAPI::fromJsonValue(d->vitality_scoring_version, json[QString("vitalityScoringVersion")]);
    d->vitality_scoring_version_isSet = !json[QString("vitalityScoringVersion")].isNull() && d->vitality_scoring_version_isValid;
}

QString OAILivePhoto::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAILivePhoto::asJsonObject() const {
    Q_D(const OAILivePhoto);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->content_id_isSet) {
        obj.insert(QString("contentId"), ::OpenAPI::toJsonValue(d->content_id));
    }
    if (d->still_image_time_us_isSet) {
        obj.insert(QString("stillImageTimeUs"), ::OpenAPI::toJsonValue(d->still_image_time_us));
    }
    if (d->r_auto_isSet) {
        obj.insert(QString("auto"), ::OpenAPI::toJsonValue(d->r_auto));
    }
    if (d->vitality_score_isSet) {
        obj.insert(QString("vitalityScore"), ::OpenAPI::toJsonValue(d->vitality_score));
    }
    if (d->vitality_scoring_version_isSet) {
        obj.insert(QString("vitalityScoringVersion"), ::OpenAPI::toJsonValue(d->vitality_scoring_version));
    }
    return obj;
}

QString OAILivePhoto::getContentId() const {
    Q_D(const OAILivePhoto);
    if(!d){
        return {};
    }
    return d->content_id;
}
void OAILivePhoto::setContentId(const QString &content_id) {
    Q_D(OAILivePhoto);
    Q_ASSERT(d);

    d->content_id = content_id;
    d->content_id_isSet = true;
}

bool OAILivePhoto::is_content_id_Set() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }

    return d->content_id_isSet;
}

bool OAILivePhoto::is_content_id_Valid() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }
    return d->content_id_isValid;
}

qint64 OAILivePhoto::getStillImageTimeUs() const {
    Q_D(const OAILivePhoto);
    if(!d){
        return {};
    }
    return d->still_image_time_us;
}
void OAILivePhoto::setStillImageTimeUs(const qint64 &still_image_time_us) {
    Q_D(OAILivePhoto);
    Q_ASSERT(d);

    d->still_image_time_us = still_image_time_us;
    d->still_image_time_us_isSet = true;
}

bool OAILivePhoto::is_still_image_time_us_Set() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }

    return d->still_image_time_us_isSet;
}

bool OAILivePhoto::is_still_image_time_us_Valid() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }
    return d->still_image_time_us_isValid;
}

bool OAILivePhoto::isRAuto() const {
    Q_D(const OAILivePhoto);
    if(!d){
        return {};
    }
    return d->r_auto;
}
void OAILivePhoto::setRAuto(const bool &r_auto) {
    Q_D(OAILivePhoto);
    Q_ASSERT(d);

    d->r_auto = r_auto;
    d->r_auto_isSet = true;
}

bool OAILivePhoto::is_r_auto_Set() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }

    return d->r_auto_isSet;
}

bool OAILivePhoto::is_r_auto_Valid() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }
    return d->r_auto_isValid;
}

double OAILivePhoto::getVitalityScore() const {
    Q_D(const OAILivePhoto);
    if(!d){
        return {};
    }
    return d->vitality_score;
}
void OAILivePhoto::setVitalityScore(const double &vitality_score) {
    Q_D(OAILivePhoto);
    Q_ASSERT(d);

    d->vitality_score = vitality_score;
    d->vitality_score_isSet = true;
}

bool OAILivePhoto::is_vitality_score_Set() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }

    return d->vitality_score_isSet;
}

bool OAILivePhoto::is_vitality_score_Valid() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }
    return d->vitality_score_isValid;
}

qint64 OAILivePhoto::getVitalityScoringVersion() const {
    Q_D(const OAILivePhoto);
    if(!d){
        return {};
    }
    return d->vitality_scoring_version;
}
void OAILivePhoto::setVitalityScoringVersion(const qint64 &vitality_scoring_version) {
    Q_D(OAILivePhoto);
    Q_ASSERT(d);

    d->vitality_scoring_version = vitality_scoring_version;
    d->vitality_scoring_version_isSet = true;
}

bool OAILivePhoto::is_vitality_scoring_version_Set() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }

    return d->vitality_scoring_version_isSet;
}

bool OAILivePhoto::is_vitality_scoring_version_Valid() const{
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }
    return d->vitality_scoring_version_isValid;
}

bool OAILivePhoto::isSet() const {
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->content_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->still_image_time_us_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->r_auto_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->vitality_score_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->vitality_scoring_version_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAILivePhoto::isValid() const {
    Q_D(const OAILivePhoto);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->content_id_isValid && true;
}

} // namespace OpenAPI
