// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIMetricDefinition.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIMetricDefinitionPrivate {
    friend class OAIMetricDefinition;

     QString kind;
     bool kind_isSet;
     bool kind_isValid;
};

OAIMetricDefinition::OAIMetricDefinition()
    : d_ptr()
{
}

OAIMetricDefinition::OAIMetricDefinition(const OAIMetricDefinition& other)
    : d_ptr(other.d_ptr)
{
}

OAIMetricDefinition::OAIMetricDefinition(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIMetricDefinition::~OAIMetricDefinition() = default;

void OAIMetricDefinition::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIMetricDefinitionPrivate{});

        Q_D(OAIMetricDefinition);


        d->kind_isSet = false;
        d->kind_isValid = false;
    }
}

void OAIMetricDefinition::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIMetricDefinition::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIMetricDefinition);

    d->kind_isValid = ::OpenAPI::fromJsonValue(d->kind, json[QString("kind")]);
    d->kind_isSet = !json[QString("kind")].isNull() && d->kind_isValid;
}

QString OAIMetricDefinition::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIMetricDefinition::asJsonObject() const {
    Q_D(const OAIMetricDefinition);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->kind_isSet) {
        obj.insert(QString("kind"), ::OpenAPI::toJsonValue(d->kind));
    }
    return obj;
}

QString OAIMetricDefinition::getKind() const {
    Q_D(const OAIMetricDefinition);
    if(!d){
        return {};
    }
    return d->kind;
}
void OAIMetricDefinition::setKind(const QString &kind) {
    Q_D(OAIMetricDefinition);
    Q_ASSERT(d);

    d->kind = kind;
    d->kind_isSet = true;
}

bool OAIMetricDefinition::is_kind_Set() const{
    Q_D(const OAIMetricDefinition);
    if(!d){
        return false;
    }

    return d->kind_isSet;
}

bool OAIMetricDefinition::is_kind_Valid() const{
    Q_D(const OAIMetricDefinition);
    if(!d){
        return false;
    }
    return d->kind_isValid;
}

bool OAIMetricDefinition::isSet() const {
    Q_D(const OAIMetricDefinition);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->kind_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIMetricDefinition::isValid() const {
    Q_D(const OAIMetricDefinition);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->kind_isValid && true;
}

} // namespace OpenAPI
