// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIMotionPhoto.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIMotionPhotoPrivate {
    friend class OAIMotionPhoto;

     qint32 version;
     bool version_isSet;
     bool version_isValid;

     qint64 presentation_timestamp_us;
     bool presentation_timestamp_us_isSet;
     bool presentation_timestamp_us_isValid;

     qint64 video_size;
     bool video_size_isSet;
     bool video_size_isValid;
};

OAIMotionPhoto::OAIMotionPhoto()
    : d_ptr()
{
}

OAIMotionPhoto::OAIMotionPhoto(const OAIMotionPhoto& other)
    : d_ptr(other.d_ptr)
{
}

OAIMotionPhoto::OAIMotionPhoto(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIMotionPhoto::~OAIMotionPhoto() = default;

void OAIMotionPhoto::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIMotionPhotoPrivate{});

        Q_D(OAIMotionPhoto);


        d->version_isSet = false;
        d->version_isValid = false;

        d->presentation_timestamp_us_isSet = false;
        d->presentation_timestamp_us_isValid = false;

        d->video_size_isSet = false;
        d->video_size_isValid = false;
    }
}

void OAIMotionPhoto::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIMotionPhoto::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIMotionPhoto);

    d->version_isValid = ::OpenAPI::fromJsonValue(d->version, json[QString("version")]);
    d->version_isSet = !json[QString("version")].isNull() && d->version_isValid;

    d->presentation_timestamp_us_isValid = ::OpenAPI::fromJsonValue(d->presentation_timestamp_us, json[QString("presentationTimestampUs")]);
    d->presentation_timestamp_us_isSet = !json[QString("presentationTimestampUs")].isNull() && d->presentation_timestamp_us_isValid;

    d->video_size_isValid = ::OpenAPI::fromJsonValue(d->video_size, json[QString("videoSize")]);
    d->video_size_isSet = !json[QString("videoSize")].isNull() && d->video_size_isValid;
}

QString OAIMotionPhoto::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIMotionPhoto::asJsonObject() const {
    Q_D(const OAIMotionPhoto);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->version_isSet) {
        obj.insert(QString("version"), ::OpenAPI::toJsonValue(d->version));
    }
    if (d->presentation_timestamp_us_isSet) {
        obj.insert(QString("presentationTimestampUs"), ::OpenAPI::toJsonValue(d->presentation_timestamp_us));
    }
    if (d->video_size_isSet) {
        obj.insert(QString("videoSize"), ::OpenAPI::toJsonValue(d->video_size));
    }
    return obj;
}

qint32 OAIMotionPhoto::getVersion() const {
    Q_D(const OAIMotionPhoto);
    if(!d){
        return {};
    }
    return d->version;
}
void OAIMotionPhoto::setVersion(const qint32 &version) {
    Q_D(OAIMotionPhoto);
    Q_ASSERT(d);

    d->version = version;
    d->version_isSet = true;
}

bool OAIMotionPhoto::is_version_Set() const{
    Q_D(const OAIMotionPhoto);
    if(!d){
        return false;
    }

    return d->version_isSet;
}

bool OAIMotionPhoto::is_version_Valid() const{
    Q_D(const OAIMotionPhoto);
    if(!d){
        return false;
    }
    return d->version_isValid;
}

qint64 OAIMotionPhoto::getPresentationTimestampUs() const {
    Q_D(const OAIMotionPhoto);
    if(!d){
        return {};
    }
    return d->presentation_timestamp_us;
}
void OAIMotionPhoto::setPresentationTimestampUs(const qint64 &presentation_timestamp_us) {
    Q_D(OAIMotionPhoto);
    Q_ASSERT(d);

    d->presentation_timestamp_us = presentation_timestamp_us;
    d->presentation_timestamp_us_isSet = true;
}

bool OAIMotionPhoto::is_presentation_timestamp_us_Set() const{
    Q_D(const OAIMotionPhoto);
    if(!d){
        return false;
    }

    return d->presentation_timestamp_us_isSet;
}

bool OAIMotionPhoto::is_presentation_timestamp_us_Valid() const{
    Q_D(const OAIMotionPhoto);
    if(!d){
        return false;
    }
    return d->presentation_timestamp_us_isValid;
}

qint64 OAIMotionPhoto::getVideoSize() const {
    Q_D(const OAIMotionPhoto);
    if(!d){
        return {};
    }
    return d->video_size;
}
void OAIMotionPhoto::setVideoSize(const qint64 &video_size) {
    Q_D(OAIMotionPhoto);
    Q_ASSERT(d);

    d->video_size = video_size;
    d->video_size_isSet = true;
}

bool OAIMotionPhoto::is_video_size_Set() const{
    Q_D(const OAIMotionPhoto);
    if(!d){
        return false;
    }

    return d->video_size_isSet;
}

bool OAIMotionPhoto::is_video_size_Valid() const{
    Q_D(const OAIMotionPhoto);
    if(!d){
        return false;
    }
    return d->video_size_isValid;
}

bool OAIMotionPhoto::isSet() const {
    Q_D(const OAIMotionPhoto);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->version_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->presentation_timestamp_us_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->video_size_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIMotionPhoto::isValid() const {
    Q_D(const OAIMotionPhoto);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
