// api-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIMePhotoApi_H
#define OAI_OAIMePhotoApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"
#include "OAIOauth.h"

#include "OAIHttpFileElement.h"
#include "OAIOdata_error.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIMePhotoApi : public QObject {
    Q_OBJECT

public:
    OAIMePhotoApi(const int timeOut = 0);
    ~OAIMePhotoApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);


    void deleteOwnUserPhoto();


    void getOwnUserPhoto();

    /**
    * @param[in]  body OAIHttpFileElement [optional]
    */
    void updateOwnUserPhotoPatch(const ::OpenAPI::OptionalParam<OAIHttpFileElement> &body = ::OpenAPI::OptionalParam<OAIHttpFileElement>());

    /**
    * @param[in]  body OAIHttpFileElement [optional]
    */
    void updateOwnUserPhotoPut(const ::OpenAPI::OptionalParam<OAIHttpFileElement> &body = ::OpenAPI::OptionalParam<OAIHttpFileElement>());


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIHttpRequestInput _latestInput;
    OAIHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void deleteOwnUserPhotoCallback(OAIHttpRequestWorker *worker);
    void getOwnUserPhotoCallback(OAIHttpRequestWorker *worker);
    void updateOwnUserPhotoPatchCallback(OAIHttpRequestWorker *worker);
    void updateOwnUserPhotoPutCallback(OAIHttpRequestWorker *worker);

signals:

    void deleteOwnUserPhotoSignal();
    void getOwnUserPhotoSignal(OAIHttpFileElement summary);
    void updateOwnUserPhotoPatchSignal();
    void updateOwnUserPhotoPutSignal();

    void deleteOwnUserPhotoSignalFull(OAIHttpRequestWorker *worker);
    void getOwnUserPhotoSignalFull(OAIHttpRequestWorker *worker, OAIHttpFileElement summary);
    void updateOwnUserPhotoPatchSignalFull(OAIHttpRequestWorker *worker);
    void updateOwnUserPhotoPutSignalFull(OAIHttpRequestWorker *worker);

    void deleteOwnUserPhotoSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void getOwnUserPhotoSignalE(OAIHttpFileElement summary, QNetworkReply::NetworkError error_type, QString error_str);
    void updateOwnUserPhotoPatchSignalE(QNetworkReply::NetworkError error_type, QString error_str);
    void updateOwnUserPhotoPutSignalE(QNetworkReply::NetworkError error_type, QString error_str);

    void deleteOwnUserPhotoSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void getOwnUserPhotoSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void updateOwnUserPhotoPatchSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void updateOwnUserPhotoPutSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public slots:
    void tokenAvailable();
    
};

} // namespace OpenAPI
#endif
