// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIMotionPhoto.h
 *
 * Motion Photo metadata. A Motion Photo is a still image with a short video clip appended to the end of the file. The presence of this facet on a driveItem indicates that the item is a Motion Photo; absence indicates it is not.  Based on the Google Motion Photo format v1.0 specification: https://developer.android.com/media/platform/motion-photo-format 
 */

#ifndef OAIMotionPhoto_H
#define OAIMotionPhoto_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIMotionPhotoPrivate;

class OAIMotionPhoto : public OAIObject {
public:
    OAIMotionPhoto();
    OAIMotionPhoto(const OAIMotionPhoto &other);
    OAIMotionPhoto(QString json);
    ~OAIMotionPhoto() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getVersion() const;
    void setVersion(const qint32 &version);
    bool is_version_Set() const;
    bool is_version_Valid() const;

    qint64 getPresentationTimestampUs() const;
    void setPresentationTimestampUs(const qint64 &presentation_timestamp_us);
    bool is_presentation_timestamp_us_Set() const;
    bool is_presentation_timestamp_us_Valid() const;

    qint64 getVideoSize() const;
    void setVideoSize(const qint64 &video_size);
    bool is_video_size_Set() const;
    bool is_video_size_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIMotionPhoto)
    QSharedPointer<OAIMotionPhotoPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIMotionPhoto)

#endif // OAIMotionPhoto_H
