// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPendingOperations_pendingContentUpdate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIPendingOperations_pendingContentUpdatePrivate {
    friend class OAIPendingOperations_pendingContentUpdate;

     QDateTime queued_date_time;
     bool queued_date_time_isSet;
     bool queued_date_time_isValid;
};

OAIPendingOperations_pendingContentUpdate::OAIPendingOperations_pendingContentUpdate()
    : d_ptr()
{
}

OAIPendingOperations_pendingContentUpdate::OAIPendingOperations_pendingContentUpdate(const OAIPendingOperations_pendingContentUpdate& other)
    : d_ptr(other.d_ptr)
{
}

OAIPendingOperations_pendingContentUpdate::OAIPendingOperations_pendingContentUpdate(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIPendingOperations_pendingContentUpdate::~OAIPendingOperations_pendingContentUpdate() = default;

void OAIPendingOperations_pendingContentUpdate::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIPendingOperations_pendingContentUpdatePrivate{});

        Q_D(OAIPendingOperations_pendingContentUpdate);


        d->queued_date_time_isSet = false;
        d->queued_date_time_isValid = false;
    }
}

void OAIPendingOperations_pendingContentUpdate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPendingOperations_pendingContentUpdate::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIPendingOperations_pendingContentUpdate);

    d->queued_date_time_isValid = ::OpenAPI::fromJsonValue(d->queued_date_time, json[QString("queuedDateTime")]);
    d->queued_date_time_isSet = !json[QString("queuedDateTime")].isNull() && d->queued_date_time_isValid;
}

QString OAIPendingOperations_pendingContentUpdate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPendingOperations_pendingContentUpdate::asJsonObject() const {
    Q_D(const OAIPendingOperations_pendingContentUpdate);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->queued_date_time_isSet) {
        obj.insert(QString("queuedDateTime"), ::OpenAPI::toJsonValue(d->queued_date_time));
    }
    return obj;
}

QDateTime OAIPendingOperations_pendingContentUpdate::getQueuedDateTime() const {
    Q_D(const OAIPendingOperations_pendingContentUpdate);
    if(!d){
        return {};
    }
    return d->queued_date_time;
}
void OAIPendingOperations_pendingContentUpdate::setQueuedDateTime(const QDateTime &queued_date_time) {
    Q_D(OAIPendingOperations_pendingContentUpdate);
    Q_ASSERT(d);

    d->queued_date_time = queued_date_time;
    d->queued_date_time_isSet = true;
}

bool OAIPendingOperations_pendingContentUpdate::is_queued_date_time_Set() const{
    Q_D(const OAIPendingOperations_pendingContentUpdate);
    if(!d){
        return false;
    }

    return d->queued_date_time_isSet;
}

bool OAIPendingOperations_pendingContentUpdate::is_queued_date_time_Valid() const{
    Q_D(const OAIPendingOperations_pendingContentUpdate);
    if(!d){
        return false;
    }
    return d->queued_date_time_isValid;
}

bool OAIPendingOperations_pendingContentUpdate::isSet() const {
    Q_D(const OAIPendingOperations_pendingContentUpdate);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->queued_date_time_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPendingOperations_pendingContentUpdate::isValid() const {
    Q_D(const OAIPendingOperations_pendingContentUpdate);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
