// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIPendingOperations.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIPendingOperationsPrivate {
    friend class OAIPendingOperations;

     OAIPendingOperations_pendingContentUpdate pending_content_update;
     bool pending_content_update_isSet;
     bool pending_content_update_isValid;
};

OAIPendingOperations::OAIPendingOperations()
    : d_ptr()
{
}

OAIPendingOperations::OAIPendingOperations(const OAIPendingOperations& other)
    : d_ptr(other.d_ptr)
{
}

OAIPendingOperations::OAIPendingOperations(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIPendingOperations::~OAIPendingOperations() = default;

void OAIPendingOperations::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIPendingOperationsPrivate{});

        Q_D(OAIPendingOperations);


        d->pending_content_update_isSet = false;
        d->pending_content_update_isValid = false;
    }
}

void OAIPendingOperations::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIPendingOperations::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIPendingOperations);

    d->pending_content_update_isValid = ::OpenAPI::fromJsonValue(d->pending_content_update, json[QString("pendingContentUpdate")]);
    d->pending_content_update_isSet = !json[QString("pendingContentUpdate")].isNull() && d->pending_content_update_isValid;
}

QString OAIPendingOperations::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIPendingOperations::asJsonObject() const {
    Q_D(const OAIPendingOperations);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->pending_content_update.isSet()) {
        obj.insert(QString("pendingContentUpdate"), ::OpenAPI::toJsonValue(d->pending_content_update));
    }
    return obj;
}

OAIPendingOperations_pendingContentUpdate OAIPendingOperations::getPendingContentUpdate() const {
    Q_D(const OAIPendingOperations);
    if(!d){
        return {};
    }
    return d->pending_content_update;
}
void OAIPendingOperations::setPendingContentUpdate(const OAIPendingOperations_pendingContentUpdate &pending_content_update) {
    Q_D(OAIPendingOperations);
    Q_ASSERT(d);

    d->pending_content_update = pending_content_update;
    d->pending_content_update_isSet = true;
}

bool OAIPendingOperations::is_pending_content_update_Set() const{
    Q_D(const OAIPendingOperations);
    if(!d){
        return false;
    }

    return d->pending_content_update_isSet;
}

bool OAIPendingOperations::is_pending_content_update_Valid() const{
    Q_D(const OAIPendingOperations);
    if(!d){
        return false;
    }
    return d->pending_content_update_isValid;
}

bool OAIPendingOperations::isSet() const {
    Q_D(const OAIPendingOperations);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->pending_content_update.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIPendingOperations::isValid() const {
    Q_D(const OAIPendingOperations);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
