// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIPendingOperations_pendingContentUpdate.h
 *
 * An update to the item&#39;s content has not completed, for example post-processing such as virus scanning after an upload. MS Graph does not specify how reads behave while this is present; in OpenCloud content requests fail. 
 */

#ifndef OAIPendingOperations_pendingContentUpdate_H
#define OAIPendingOperations_pendingContentUpdate_H

#include <QJsonObject>

#include <QDateTime>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAIPendingOperations_pendingContentUpdatePrivate;

class OAIPendingOperations_pendingContentUpdate : public OAIObject {
public:
    OAIPendingOperations_pendingContentUpdate();
    OAIPendingOperations_pendingContentUpdate(const OAIPendingOperations_pendingContentUpdate &other);
    OAIPendingOperations_pendingContentUpdate(QString json);
    ~OAIPendingOperations_pendingContentUpdate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QDateTime getQueuedDateTime() const;
    void setQueuedDateTime(const QDateTime &queued_date_time);
    bool is_queued_date_time_Set() const;
    bool is_queued_date_time_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIPendingOperations_pendingContentUpdate)
    QSharedPointer<OAIPendingOperations_pendingContentUpdatePrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPendingOperations_pendingContentUpdate)

#endif // OAIPendingOperations_pendingContentUpdate_H
