// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIPendingOperations.h
 *
 * Present while operations affecting the item&#39;s content have not completed, whether still queued or already running. While present, requests for the item&#39;s content fail, the content is withheld until processing completes and the facet disappears. 
 */

#ifndef OAIPendingOperations_H
#define OAIPendingOperations_H

#include <QJsonObject>

#include "OAIPendingOperations_pendingContentUpdate.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIPendingOperations_pendingContentUpdate;


class OAIPendingOperationsPrivate;

class OAIPendingOperations : public OAIObject {
public:
    OAIPendingOperations();
    OAIPendingOperations(const OAIPendingOperations &other);
    OAIPendingOperations(QString json);
    ~OAIPendingOperations() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIPendingOperations_pendingContentUpdate getPendingContentUpdate() const;
    void setPendingContentUpdate(const OAIPendingOperations_pendingContentUpdate &pending_content_update);
    bool is_pending_content_update_Set() const;
    bool is_pending_content_update_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIPendingOperations)
    QSharedPointer<OAIPendingOperationsPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPendingOperations)

#endif // OAIPendingOperations_H
