// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIRecipient.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIRecipientPrivate {
    friend class OAIRecipient;

     OAIEmailAddress email_address;
     bool email_address_isSet;
     bool email_address_isValid;
};

OAIRecipient::OAIRecipient()
    : d_ptr()
{
}

OAIRecipient::OAIRecipient(const OAIRecipient& other)
    : d_ptr(other.d_ptr)
{
}

OAIRecipient::OAIRecipient(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIRecipient::~OAIRecipient() = default;

void OAIRecipient::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIRecipientPrivate{});

        Q_D(OAIRecipient);


        d->email_address_isSet = false;
        d->email_address_isValid = false;
    }
}

void OAIRecipient::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIRecipient::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIRecipient);

    d->email_address_isValid = ::OpenAPI::fromJsonValue(d->email_address, json[QString("emailAddress")]);
    d->email_address_isSet = !json[QString("emailAddress")].isNull() && d->email_address_isValid;
}

QString OAIRecipient::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIRecipient::asJsonObject() const {
    Q_D(const OAIRecipient);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->email_address.isSet()) {
        obj.insert(QString("emailAddress"), ::OpenAPI::toJsonValue(d->email_address));
    }
    return obj;
}

OAIEmailAddress OAIRecipient::getEmailAddress() const {
    Q_D(const OAIRecipient);
    if(!d){
        return {};
    }
    return d->email_address;
}
void OAIRecipient::setEmailAddress(const OAIEmailAddress &email_address) {
    Q_D(OAIRecipient);
    Q_ASSERT(d);

    d->email_address = email_address;
    d->email_address_isSet = true;
}

bool OAIRecipient::is_email_address_Set() const{
    Q_D(const OAIRecipient);
    if(!d){
        return false;
    }

    return d->email_address_isSet;
}

bool OAIRecipient::is_email_address_Valid() const{
    Q_D(const OAIRecipient);
    if(!d){
        return false;
    }
    return d->email_address_isValid;
}

bool OAIRecipient::isSet() const {
    Q_D(const OAIRecipient);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->email_address.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIRecipient::isValid() const {
    Q_D(const OAIRecipient);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
