// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRecipient.h
 *
 * Represents a recipient of an invitation.
 */

#ifndef OAIRecipient_H
#define OAIRecipient_H

#include <QJsonObject>

#include "OAIEmailAddress.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIEmailAddress;


class OAIRecipientPrivate;

class OAIRecipient : public OAIObject {
public:
    OAIRecipient();
    OAIRecipient(const OAIRecipient &other);
    OAIRecipient(QString json);
    ~OAIRecipient() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIEmailAddress getEmailAddress() const;
    void setEmailAddress(const OAIEmailAddress &email_address);
    bool is_email_address_Set() const;
    bool is_email_address_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAIRecipient)
    QSharedPointer<OAIRecipientPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIRecipient)

#endif // OAIRecipient_H
