// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchQuery_200_response.h
 *
 * 
 */

#ifndef OAISearchQuery_200_response_H
#define OAISearchQuery_200_response_H

#include <QJsonObject>

#include "OAISearchResponse.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchResponse;


class OAISearchQuery_200_responsePrivate;

class OAISearchQuery_200_response : public OAIObject {
public:
    OAISearchQuery_200_response();
    OAISearchQuery_200_response(const OAISearchQuery_200_response &other);
    OAISearchQuery_200_response(QString json);
    ~OAISearchQuery_200_response() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAISearchResponse> getValue() const;
    void setValue(const QList<OAISearchResponse> &value);
    bool is_value_Set() const;
    bool is_value_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchQuery_200_response)
    QSharedPointer<OAISearchQuery_200_responsePrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchQuery_200_response)

#endif // OAISearchQuery_200_response_H
