// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchMetric.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchMetricPrivate {
    friend class OAISearchMetric;

     QString kind;
     bool kind_isSet;
     bool kind_isValid;

     double value;
     bool value_isSet;
     bool value_isValid;
};

OAISearchMetric::OAISearchMetric()
    : d_ptr()
{
}

OAISearchMetric::OAISearchMetric(const OAISearchMetric& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchMetric::OAISearchMetric(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchMetric::~OAISearchMetric() = default;

void OAISearchMetric::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchMetricPrivate{});

        Q_D(OAISearchMetric);


        d->kind_isSet = false;
        d->kind_isValid = false;

        d->value_isSet = false;
        d->value_isValid = false;
    }
}

void OAISearchMetric::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchMetric::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchMetric);

    d->kind_isValid = ::OpenAPI::fromJsonValue(d->kind, json[QString("kind")]);
    d->kind_isSet = !json[QString("kind")].isNull() && d->kind_isValid;

    d->value_isValid = ::OpenAPI::fromJsonValue(d->value, json[QString("value")]);
    d->value_isSet = !json[QString("value")].isNull() && d->value_isValid;
}

QString OAISearchMetric::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchMetric::asJsonObject() const {
    Q_D(const OAISearchMetric);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->kind_isSet) {
        obj.insert(QString("kind"), ::OpenAPI::toJsonValue(d->kind));
    }
    if (d->value_isSet) {
        obj.insert(QString("value"), ::OpenAPI::toJsonValue(d->value));
    }
    return obj;
}

QString OAISearchMetric::getKind() const {
    Q_D(const OAISearchMetric);
    if(!d){
        return {};
    }
    return d->kind;
}
void OAISearchMetric::setKind(const QString &kind) {
    Q_D(OAISearchMetric);
    Q_ASSERT(d);

    d->kind = kind;
    d->kind_isSet = true;
}

bool OAISearchMetric::is_kind_Set() const{
    Q_D(const OAISearchMetric);
    if(!d){
        return false;
    }

    return d->kind_isSet;
}

bool OAISearchMetric::is_kind_Valid() const{
    Q_D(const OAISearchMetric);
    if(!d){
        return false;
    }
    return d->kind_isValid;
}

double OAISearchMetric::getValue() const {
    Q_D(const OAISearchMetric);
    if(!d){
        return {};
    }
    return d->value;
}
void OAISearchMetric::setValue(const double &value) {
    Q_D(OAISearchMetric);
    Q_ASSERT(d);

    d->value = value;
    d->value_isSet = true;
}

bool OAISearchMetric::is_value_Set() const{
    Q_D(const OAISearchMetric);
    if(!d){
        return false;
    }

    return d->value_isSet;
}

bool OAISearchMetric::is_value_Valid() const{
    Q_D(const OAISearchMetric);
    if(!d){
        return false;
    }
    return d->value_isValid;
}

bool OAISearchMetric::isSet() const {
    Q_D(const OAISearchMetric);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->kind_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->value_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchMetric::isValid() const {
    Q_D(const OAISearchMetric);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
