// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchResponse.h
 *
 * Represents the response for an individual search request. Follows the [MS Graph searchResponse](https://learn.microsoft.com/en-us/graph/api/resources/searchresponse) resource type. 
 */

#ifndef OAISearchResponse_H
#define OAISearchResponse_H

#include <QJsonObject>

#include "OAISearchHitsContainer.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchHitsContainer;


class OAISearchResponsePrivate;

class OAISearchResponse : public OAIObject {
public:
    OAISearchResponse();
    OAISearchResponse(const OAISearchResponse &other);
    OAISearchResponse(QString json);
    ~OAISearchResponse() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<QString> getSearchTerms() const;
    void setSearchTerms(const QList<QString> &search_terms);
    bool is_search_terms_Set() const;
    bool is_search_terms_Valid() const;

    QList<OAISearchHitsContainer> getHitsContainers() const;
    void setHitsContainers(const QList<OAISearchHitsContainer> &hits_containers);
    bool is_hits_containers_Set() const;
    bool is_hits_containers_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchResponse)
    QSharedPointer<OAISearchResponsePrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchResponse)

#endif // OAISearchResponse_H
