// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchHitsContainer.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchHitsContainerPrivate {
    friend class OAISearchHitsContainer;

     QList<OAISearchHit> hits;
     bool hits_isSet;
     bool hits_isValid;

     qint64 total;
     bool total_isSet;
     bool total_isValid;

     bool more_results_available;
     bool more_results_available_isSet;
     bool more_results_available_isValid;

     QList<OAISearchAggregation> aggregations;
     bool aggregations_isSet;
     bool aggregations_isValid;
};

OAISearchHitsContainer::OAISearchHitsContainer()
    : d_ptr()
{
}

OAISearchHitsContainer::OAISearchHitsContainer(const OAISearchHitsContainer& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchHitsContainer::OAISearchHitsContainer(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchHitsContainer::~OAISearchHitsContainer() = default;

void OAISearchHitsContainer::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchHitsContainerPrivate{});

        Q_D(OAISearchHitsContainer);


        d->hits_isSet = false;
        d->hits_isValid = false;

        d->total_isSet = false;
        d->total_isValid = false;

        d->more_results_available_isSet = false;
        d->more_results_available_isValid = false;

        d->aggregations_isSet = false;
        d->aggregations_isValid = false;
    }
}

void OAISearchHitsContainer::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchHitsContainer::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchHitsContainer);

    d->hits_isValid = ::OpenAPI::fromJsonValue(d->hits, json[QString("hits")]);
    d->hits_isSet = !json[QString("hits")].isNull() && d->hits_isValid;

    d->total_isValid = ::OpenAPI::fromJsonValue(d->total, json[QString("total")]);
    d->total_isSet = !json[QString("total")].isNull() && d->total_isValid;

    d->more_results_available_isValid = ::OpenAPI::fromJsonValue(d->more_results_available, json[QString("moreResultsAvailable")]);
    d->more_results_available_isSet = !json[QString("moreResultsAvailable")].isNull() && d->more_results_available_isValid;

    d->aggregations_isValid = ::OpenAPI::fromJsonValue(d->aggregations, json[QString("aggregations")]);
    d->aggregations_isSet = !json[QString("aggregations")].isNull() && d->aggregations_isValid;
}

QString OAISearchHitsContainer::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchHitsContainer::asJsonObject() const {
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->hits.size() > 0) {
        obj.insert(QString("hits"), ::OpenAPI::toJsonValue(d->hits));
    }
    if (d->total_isSet) {
        obj.insert(QString("total"), ::OpenAPI::toJsonValue(d->total));
    }
    if (d->more_results_available_isSet) {
        obj.insert(QString("moreResultsAvailable"), ::OpenAPI::toJsonValue(d->more_results_available));
    }
    if (d->aggregations.size() > 0) {
        obj.insert(QString("aggregations"), ::OpenAPI::toJsonValue(d->aggregations));
    }
    return obj;
}

QList<OAISearchHit> OAISearchHitsContainer::getHits() const {
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return {};
    }
    return d->hits;
}
void OAISearchHitsContainer::setHits(const QList<OAISearchHit> &hits) {
    Q_D(OAISearchHitsContainer);
    Q_ASSERT(d);

    d->hits = hits;
    d->hits_isSet = true;
}

bool OAISearchHitsContainer::is_hits_Set() const{
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }

    return d->hits_isSet;
}

bool OAISearchHitsContainer::is_hits_Valid() const{
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }
    return d->hits_isValid;
}

qint64 OAISearchHitsContainer::getTotal() const {
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return {};
    }
    return d->total;
}
void OAISearchHitsContainer::setTotal(const qint64 &total) {
    Q_D(OAISearchHitsContainer);
    Q_ASSERT(d);

    d->total = total;
    d->total_isSet = true;
}

bool OAISearchHitsContainer::is_total_Set() const{
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }

    return d->total_isSet;
}

bool OAISearchHitsContainer::is_total_Valid() const{
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }
    return d->total_isValid;
}

bool OAISearchHitsContainer::isMoreResultsAvailable() const {
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return {};
    }
    return d->more_results_available;
}
void OAISearchHitsContainer::setMoreResultsAvailable(const bool &more_results_available) {
    Q_D(OAISearchHitsContainer);
    Q_ASSERT(d);

    d->more_results_available = more_results_available;
    d->more_results_available_isSet = true;
}

bool OAISearchHitsContainer::is_more_results_available_Set() const{
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }

    return d->more_results_available_isSet;
}

bool OAISearchHitsContainer::is_more_results_available_Valid() const{
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }
    return d->more_results_available_isValid;
}

QList<OAISearchAggregation> OAISearchHitsContainer::getAggregations() const {
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return {};
    }
    return d->aggregations;
}
void OAISearchHitsContainer::setAggregations(const QList<OAISearchAggregation> &aggregations) {
    Q_D(OAISearchHitsContainer);
    Q_ASSERT(d);

    d->aggregations = aggregations;
    d->aggregations_isSet = true;
}

bool OAISearchHitsContainer::is_aggregations_Set() const{
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }

    return d->aggregations_isSet;
}

bool OAISearchHitsContainer::is_aggregations_Valid() const{
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }
    return d->aggregations_isValid;
}

bool OAISearchHitsContainer::isSet() const {
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->hits.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->total_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->more_results_available_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->aggregations.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchHitsContainer::isValid() const {
    Q_D(const OAISearchHitsContainer);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
