// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchResponse.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchResponsePrivate {
    friend class OAISearchResponse;

     QList<QString> search_terms;
     bool search_terms_isSet;
     bool search_terms_isValid;

     QList<OAISearchHitsContainer> hits_containers;
     bool hits_containers_isSet;
     bool hits_containers_isValid;
};

OAISearchResponse::OAISearchResponse()
    : d_ptr()
{
}

OAISearchResponse::OAISearchResponse(const OAISearchResponse& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchResponse::OAISearchResponse(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchResponse::~OAISearchResponse() = default;

void OAISearchResponse::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchResponsePrivate{});

        Q_D(OAISearchResponse);


        d->search_terms_isSet = false;
        d->search_terms_isValid = false;

        d->hits_containers_isSet = false;
        d->hits_containers_isValid = false;
    }
}

void OAISearchResponse::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchResponse::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchResponse);

    d->search_terms_isValid = ::OpenAPI::fromJsonValue(d->search_terms, json[QString("searchTerms")]);
    d->search_terms_isSet = !json[QString("searchTerms")].isNull() && d->search_terms_isValid;

    d->hits_containers_isValid = ::OpenAPI::fromJsonValue(d->hits_containers, json[QString("hitsContainers")]);
    d->hits_containers_isSet = !json[QString("hitsContainers")].isNull() && d->hits_containers_isValid;
}

QString OAISearchResponse::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchResponse::asJsonObject() const {
    Q_D(const OAISearchResponse);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->search_terms.size() > 0) {
        obj.insert(QString("searchTerms"), ::OpenAPI::toJsonValue(d->search_terms));
    }
    if (d->hits_containers.size() > 0) {
        obj.insert(QString("hitsContainers"), ::OpenAPI::toJsonValue(d->hits_containers));
    }
    return obj;
}

QList<QString> OAISearchResponse::getSearchTerms() const {
    Q_D(const OAISearchResponse);
    if(!d){
        return {};
    }
    return d->search_terms;
}
void OAISearchResponse::setSearchTerms(const QList<QString> &search_terms) {
    Q_D(OAISearchResponse);
    Q_ASSERT(d);

    d->search_terms = search_terms;
    d->search_terms_isSet = true;
}

bool OAISearchResponse::is_search_terms_Set() const{
    Q_D(const OAISearchResponse);
    if(!d){
        return false;
    }

    return d->search_terms_isSet;
}

bool OAISearchResponse::is_search_terms_Valid() const{
    Q_D(const OAISearchResponse);
    if(!d){
        return false;
    }
    return d->search_terms_isValid;
}

QList<OAISearchHitsContainer> OAISearchResponse::getHitsContainers() const {
    Q_D(const OAISearchResponse);
    if(!d){
        return {};
    }
    return d->hits_containers;
}
void OAISearchResponse::setHitsContainers(const QList<OAISearchHitsContainer> &hits_containers) {
    Q_D(OAISearchResponse);
    Q_ASSERT(d);

    d->hits_containers = hits_containers;
    d->hits_containers_isSet = true;
}

bool OAISearchResponse::is_hits_containers_Set() const{
    Q_D(const OAISearchResponse);
    if(!d){
        return false;
    }

    return d->hits_containers_isSet;
}

bool OAISearchResponse::is_hits_containers_Valid() const{
    Q_D(const OAISearchResponse);
    if(!d){
        return false;
    }
    return d->hits_containers_isValid;
}

bool OAISearchResponse::isSet() const {
    Q_D(const OAISearchResponse);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->search_terms.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->hits_containers.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchResponse::isValid() const {
    Q_D(const OAISearchResponse);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
