// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchAggregation.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchAggregationPrivate {
    friend class OAISearchAggregation;

     QString field;
     bool field_isSet;
     bool field_isValid;

     QList<OAISearchBucket> buckets;
     bool buckets_isSet;
     bool buckets_isValid;

     OAISearchMetric libre_graph_metric;
     bool libre_graph_metric_isSet;
     bool libre_graph_metric_isValid;
};

OAISearchAggregation::OAISearchAggregation()
    : d_ptr()
{
}

OAISearchAggregation::OAISearchAggregation(const OAISearchAggregation& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchAggregation::OAISearchAggregation(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchAggregation::~OAISearchAggregation() = default;

void OAISearchAggregation::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchAggregationPrivate{});

        Q_D(OAISearchAggregation);


        d->field_isSet = false;
        d->field_isValid = false;

        d->buckets_isSet = false;
        d->buckets_isValid = false;

        d->libre_graph_metric_isSet = false;
        d->libre_graph_metric_isValid = false;
    }
}

void OAISearchAggregation::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchAggregation::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchAggregation);

    d->field_isValid = ::OpenAPI::fromJsonValue(d->field, json[QString("field")]);
    d->field_isSet = !json[QString("field")].isNull() && d->field_isValid;

    d->buckets_isValid = ::OpenAPI::fromJsonValue(d->buckets, json[QString("buckets")]);
    d->buckets_isSet = !json[QString("buckets")].isNull() && d->buckets_isValid;

    d->libre_graph_metric_isValid = ::OpenAPI::fromJsonValue(d->libre_graph_metric, json[QString("@libre.graph.metric")]);
    d->libre_graph_metric_isSet = !json[QString("@libre.graph.metric")].isNull() && d->libre_graph_metric_isValid;
}

QString OAISearchAggregation::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchAggregation::asJsonObject() const {
    Q_D(const OAISearchAggregation);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->field_isSet) {
        obj.insert(QString("field"), ::OpenAPI::toJsonValue(d->field));
    }
    if (d->buckets.size() > 0) {
        obj.insert(QString("buckets"), ::OpenAPI::toJsonValue(d->buckets));
    }
    if (d->libre_graph_metric.isSet()) {
        obj.insert(QString("@libre.graph.metric"), ::OpenAPI::toJsonValue(d->libre_graph_metric));
    }
    return obj;
}

QString OAISearchAggregation::getField() const {
    Q_D(const OAISearchAggregation);
    if(!d){
        return {};
    }
    return d->field;
}
void OAISearchAggregation::setField(const QString &field) {
    Q_D(OAISearchAggregation);
    Q_ASSERT(d);

    d->field = field;
    d->field_isSet = true;
}

bool OAISearchAggregation::is_field_Set() const{
    Q_D(const OAISearchAggregation);
    if(!d){
        return false;
    }

    return d->field_isSet;
}

bool OAISearchAggregation::is_field_Valid() const{
    Q_D(const OAISearchAggregation);
    if(!d){
        return false;
    }
    return d->field_isValid;
}

QList<OAISearchBucket> OAISearchAggregation::getBuckets() const {
    Q_D(const OAISearchAggregation);
    if(!d){
        return {};
    }
    return d->buckets;
}
void OAISearchAggregation::setBuckets(const QList<OAISearchBucket> &buckets) {
    Q_D(OAISearchAggregation);
    Q_ASSERT(d);

    d->buckets = buckets;
    d->buckets_isSet = true;
}

bool OAISearchAggregation::is_buckets_Set() const{
    Q_D(const OAISearchAggregation);
    if(!d){
        return false;
    }

    return d->buckets_isSet;
}

bool OAISearchAggregation::is_buckets_Valid() const{
    Q_D(const OAISearchAggregation);
    if(!d){
        return false;
    }
    return d->buckets_isValid;
}

OAISearchMetric OAISearchAggregation::getLibreGraphMetric() const {
    Q_D(const OAISearchAggregation);
    if(!d){
        return {};
    }
    return d->libre_graph_metric;
}
void OAISearchAggregation::setLibreGraphMetric(const OAISearchMetric &libre_graph_metric) {
    Q_D(OAISearchAggregation);
    Q_ASSERT(d);

    d->libre_graph_metric = libre_graph_metric;
    d->libre_graph_metric_isSet = true;
}

bool OAISearchAggregation::is_libre_graph_metric_Set() const{
    Q_D(const OAISearchAggregation);
    if(!d){
        return false;
    }

    return d->libre_graph_metric_isSet;
}

bool OAISearchAggregation::is_libre_graph_metric_Valid() const{
    Q_D(const OAISearchAggregation);
    if(!d){
        return false;
    }
    return d->libre_graph_metric_isValid;
}

bool OAISearchAggregation::isSet() const {
    Q_D(const OAISearchAggregation);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->field_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->buckets.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->libre_graph_metric.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchAggregation::isValid() const {
    Q_D(const OAISearchAggregation);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
