// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchMetric.h
 *
 * The result of a metric aggregation, the counterpart of &#x60;buckets&#x60; for aggregations requested with a &#x60;@libre.graph.metricDefinition&#x60;. Absent for terms and range aggregations. Libregraph extension not present in MS Graph. 
 */

#ifndef OAISearchMetric_H
#define OAISearchMetric_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAISearchMetricPrivate;

class OAISearchMetric : public OAIObject {
public:
    OAISearchMetric();
    OAISearchMetric(const OAISearchMetric &other);
    OAISearchMetric(QString json);
    ~OAISearchMetric() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getKind() const;
    void setKind(const QString &kind);
    bool is_kind_Set() const;
    bool is_kind_Valid() const;

    double getValue() const;
    void setValue(const double &value);
    bool is_value_Set() const;
    bool is_value_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchMetric)
    QSharedPointer<OAISearchMetricPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchMetric)

#endif // OAISearchMetric_H
