// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchHitsContainer.h
 *
 * Contains a collection of search results. Follows the [MS Graph searchHitsContainer](https://learn.microsoft.com/en-us/graph/api/resources/searchhitscontainer) resource type. 
 */

#ifndef OAISearchHitsContainer_H
#define OAISearchHitsContainer_H

#include <QJsonObject>

#include "OAISearchAggregation.h"
#include "OAISearchHit.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchHit;
class OAISearchAggregation;


class OAISearchHitsContainerPrivate;

class OAISearchHitsContainer : public OAIObject {
public:
    OAISearchHitsContainer();
    OAISearchHitsContainer(const OAISearchHitsContainer &other);
    OAISearchHitsContainer(QString json);
    ~OAISearchHitsContainer() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAISearchHit> getHits() const;
    void setHits(const QList<OAISearchHit> &hits);
    bool is_hits_Set() const;
    bool is_hits_Valid() const;

    qint64 getTotal() const;
    void setTotal(const qint64 &total);
    bool is_total_Set() const;
    bool is_total_Valid() const;

    bool isMoreResultsAvailable() const;
    void setMoreResultsAvailable(const bool &more_results_available);
    bool is_more_results_available_Set() const;
    bool is_more_results_available_Valid() const;

    QList<OAISearchAggregation> getAggregations() const;
    void setAggregations(const QList<OAISearchAggregation> &aggregations);
    bool is_aggregations_Set() const;
    bool is_aggregations_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchHitsContainer)
    QSharedPointer<OAISearchHitsContainerPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchHitsContainer)

#endif // OAISearchHitsContainer_H
