// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchQuery_request.h
 *
 * 
 */

#ifndef OAISearchQuery_request_H
#define OAISearchQuery_request_H

#include <QJsonObject>

#include "OAISearchRequest.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchRequest;


class OAISearchQuery_requestPrivate;

class OAISearchQuery_request : public OAIObject {
public:
    OAISearchQuery_request();
    OAISearchQuery_request(const OAISearchQuery_request &other);
    OAISearchQuery_request(QString json);
    ~OAISearchQuery_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAISearchRequest> getRequests() const;
    void setRequests(const QList<OAISearchRequest> &requests);
    bool is_requests_Set() const;
    bool is_requests_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchQuery_request)
    QSharedPointer<OAISearchQuery_requestPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchQuery_request)

#endif // OAISearchQuery_request_H
