// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchBucket.h
 *
 * Represents a single bucket in a search aggregation result. Follows the [MS Graph searchBucket](https://learn.microsoft.com/en-us/graph/api/resources/searchbucket) resource type. 
 */

#ifndef OAISearchBucket_H
#define OAISearchBucket_H

#include <QJsonObject>

#include "OAISearchAggregation.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchAggregation;


class OAISearchBucketPrivate;

class OAISearchBucket : public OAIObject {
public:
    OAISearchBucket();
    OAISearchBucket(const OAISearchBucket &other);
    OAISearchBucket(QString json);
    ~OAISearchBucket() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getKey() const;
    void setKey(const QString &key);
    bool is_key_Set() const;
    bool is_key_Valid() const;

    qint64 getCount() const;
    void setCount(const qint64 &count);
    bool is_count_Set() const;
    bool is_count_Valid() const;

    QString getAggregationFilterToken() const;
    void setAggregationFilterToken(const QString &aggregation_filter_token);
    bool is_aggregation_filter_token_Set() const;
    bool is_aggregation_filter_token_Valid() const;

    QList<OAISearchAggregation> getLibreGraphSubAggregations() const;
    void setLibreGraphSubAggregations(const QList<OAISearchAggregation> &libre_graph_sub_aggregations);
    bool is_libre_graph_sub_aggregations_Set() const;
    bool is_libre_graph_sub_aggregations_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchBucket)
    QSharedPointer<OAISearchBucketPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchBucket)

#endif // OAISearchBucket_H
