// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchQuery.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchQueryPrivate {
    friend class OAISearchQuery;

     QString query_string;
     bool query_string_isSet;
     bool query_string_isValid;
};

OAISearchQuery::OAISearchQuery()
    : d_ptr()
{
}

OAISearchQuery::OAISearchQuery(const OAISearchQuery& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchQuery::OAISearchQuery(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchQuery::~OAISearchQuery() = default;

void OAISearchQuery::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchQueryPrivate{});

        Q_D(OAISearchQuery);


        d->query_string_isSet = false;
        d->query_string_isValid = false;
    }
}

void OAISearchQuery::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchQuery::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchQuery);

    d->query_string_isValid = ::OpenAPI::fromJsonValue(d->query_string, json[QString("queryString")]);
    d->query_string_isSet = !json[QString("queryString")].isNull() && d->query_string_isValid;
}

QString OAISearchQuery::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchQuery::asJsonObject() const {
    Q_D(const OAISearchQuery);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->query_string_isSet) {
        obj.insert(QString("queryString"), ::OpenAPI::toJsonValue(d->query_string));
    }
    return obj;
}

QString OAISearchQuery::getQueryString() const {
    Q_D(const OAISearchQuery);
    if(!d){
        return {};
    }
    return d->query_string;
}
void OAISearchQuery::setQueryString(const QString &query_string) {
    Q_D(OAISearchQuery);
    Q_ASSERT(d);

    d->query_string = query_string;
    d->query_string_isSet = true;
}

bool OAISearchQuery::is_query_string_Set() const{
    Q_D(const OAISearchQuery);
    if(!d){
        return false;
    }

    return d->query_string_isSet;
}

bool OAISearchQuery::is_query_string_Valid() const{
    Q_D(const OAISearchQuery);
    if(!d){
        return false;
    }
    return d->query_string_isValid;
}

bool OAISearchQuery::isSet() const {
    Q_D(const OAISearchQuery);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->query_string_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchQuery::isValid() const {
    Q_D(const OAISearchQuery);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->query_string_isValid && true;
}

} // namespace OpenAPI
