// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchAggregation.h
 *
 * Provides the details of a search aggregation in the search response. Follows the [MS Graph searchAggregation](https://learn.microsoft.com/en-us/graph/api/resources/searchaggregation) resource type. 
 */

#ifndef OAISearchAggregation_H
#define OAISearchAggregation_H

#include <QJsonObject>

#include "OAISearchBucket.h"
#include "OAISearchMetric.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchBucket;
class OAISearchMetric;


class OAISearchAggregationPrivate;

class OAISearchAggregation : public OAIObject {
public:
    OAISearchAggregation();
    OAISearchAggregation(const OAISearchAggregation &other);
    OAISearchAggregation(QString json);
    ~OAISearchAggregation() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getField() const;
    void setField(const QString &field);
    bool is_field_Set() const;
    bool is_field_Valid() const;

    QList<OAISearchBucket> getBuckets() const;
    void setBuckets(const QList<OAISearchBucket> &buckets);
    bool is_buckets_Set() const;
    bool is_buckets_Valid() const;

    OAISearchMetric getLibreGraphMetric() const;
    void setLibreGraphMetric(const OAISearchMetric &libre_graph_metric);
    bool is_libre_graph_metric_Set() const;
    bool is_libre_graph_metric_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchAggregation)
    QSharedPointer<OAISearchAggregationPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchAggregation)

#endif // OAISearchAggregation_H
