// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchRequest.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchRequestPrivate {
    friend class OAISearchRequest;

     QList<QString> entity_types;
     bool entity_types_isSet;
     bool entity_types_isValid;

     OAISearchQuery query;
     bool query_isSet;
     bool query_isValid;

     qint32 from;
     bool from_isSet;
     bool from_isValid;

     qint32 size;
     bool size_isSet;
     bool size_isValid;

     QList<OAIAggregationOption> aggregations;
     bool aggregations_isSet;
     bool aggregations_isValid;

     QList<QString> aggregation_filters;
     bool aggregation_filters_isSet;
     bool aggregation_filters_isValid;

     QList<OAISortProperty> sort_properties;
     bool sort_properties_isSet;
     bool sort_properties_isValid;
};

OAISearchRequest::OAISearchRequest()
    : d_ptr()
{
}

OAISearchRequest::OAISearchRequest(const OAISearchRequest& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchRequest::OAISearchRequest(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchRequest::~OAISearchRequest() = default;

void OAISearchRequest::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchRequestPrivate{});

        Q_D(OAISearchRequest);


        d->entity_types_isSet = false;
        d->entity_types_isValid = false;

        d->query_isSet = false;
        d->query_isValid = false;

        d->from_isSet = false;
        d->from_isValid = false;

        d->size_isSet = false;
        d->size_isValid = false;

        d->aggregations_isSet = false;
        d->aggregations_isValid = false;

        d->aggregation_filters_isSet = false;
        d->aggregation_filters_isValid = false;

        d->sort_properties_isSet = false;
        d->sort_properties_isValid = false;
    }
}

void OAISearchRequest::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchRequest::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchRequest);

    d->entity_types_isValid = ::OpenAPI::fromJsonValue(d->entity_types, json[QString("entityTypes")]);
    d->entity_types_isSet = !json[QString("entityTypes")].isNull() && d->entity_types_isValid;

    d->query_isValid = ::OpenAPI::fromJsonValue(d->query, json[QString("query")]);
    d->query_isSet = !json[QString("query")].isNull() && d->query_isValid;

    d->from_isValid = ::OpenAPI::fromJsonValue(d->from, json[QString("from")]);
    d->from_isSet = !json[QString("from")].isNull() && d->from_isValid;

    d->size_isValid = ::OpenAPI::fromJsonValue(d->size, json[QString("size")]);
    d->size_isSet = !json[QString("size")].isNull() && d->size_isValid;

    d->aggregations_isValid = ::OpenAPI::fromJsonValue(d->aggregations, json[QString("aggregations")]);
    d->aggregations_isSet = !json[QString("aggregations")].isNull() && d->aggregations_isValid;

    d->aggregation_filters_isValid = ::OpenAPI::fromJsonValue(d->aggregation_filters, json[QString("aggregationFilters")]);
    d->aggregation_filters_isSet = !json[QString("aggregationFilters")].isNull() && d->aggregation_filters_isValid;

    d->sort_properties_isValid = ::OpenAPI::fromJsonValue(d->sort_properties, json[QString("sortProperties")]);
    d->sort_properties_isSet = !json[QString("sortProperties")].isNull() && d->sort_properties_isValid;
}

QString OAISearchRequest::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchRequest::asJsonObject() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->entity_types.size() > 0) {
        obj.insert(QString("entityTypes"), ::OpenAPI::toJsonValue(d->entity_types));
    }
    if (d->query.isSet()) {
        obj.insert(QString("query"), ::OpenAPI::toJsonValue(d->query));
    }
    if (d->from_isSet) {
        obj.insert(QString("from"), ::OpenAPI::toJsonValue(d->from));
    }
    if (d->size_isSet) {
        obj.insert(QString("size"), ::OpenAPI::toJsonValue(d->size));
    }
    if (d->aggregations.size() > 0) {
        obj.insert(QString("aggregations"), ::OpenAPI::toJsonValue(d->aggregations));
    }
    if (d->aggregation_filters.size() > 0) {
        obj.insert(QString("aggregationFilters"), ::OpenAPI::toJsonValue(d->aggregation_filters));
    }
    if (d->sort_properties.size() > 0) {
        obj.insert(QString("sortProperties"), ::OpenAPI::toJsonValue(d->sort_properties));
    }
    return obj;
}

QList<QString> OAISearchRequest::getEntityTypes() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return {};
    }
    return d->entity_types;
}
void OAISearchRequest::setEntityTypes(const QList<QString> &entity_types) {
    Q_D(OAISearchRequest);
    Q_ASSERT(d);

    d->entity_types = entity_types;
    d->entity_types_isSet = true;
}

bool OAISearchRequest::is_entity_types_Set() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }

    return d->entity_types_isSet;
}

bool OAISearchRequest::is_entity_types_Valid() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    return d->entity_types_isValid;
}

OAISearchQuery OAISearchRequest::getQuery() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return {};
    }
    return d->query;
}
void OAISearchRequest::setQuery(const OAISearchQuery &query) {
    Q_D(OAISearchRequest);
    Q_ASSERT(d);

    d->query = query;
    d->query_isSet = true;
}

bool OAISearchRequest::is_query_Set() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }

    return d->query_isSet;
}

bool OAISearchRequest::is_query_Valid() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    return d->query_isValid;
}

qint32 OAISearchRequest::getFrom() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return {};
    }
    return d->from;
}
void OAISearchRequest::setFrom(const qint32 &from) {
    Q_D(OAISearchRequest);
    Q_ASSERT(d);

    d->from = from;
    d->from_isSet = true;
}

bool OAISearchRequest::is_from_Set() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }

    return d->from_isSet;
}

bool OAISearchRequest::is_from_Valid() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    return d->from_isValid;
}

qint32 OAISearchRequest::getSize() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return {};
    }
    return d->size;
}
void OAISearchRequest::setSize(const qint32 &size) {
    Q_D(OAISearchRequest);
    Q_ASSERT(d);

    d->size = size;
    d->size_isSet = true;
}

bool OAISearchRequest::is_size_Set() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }

    return d->size_isSet;
}

bool OAISearchRequest::is_size_Valid() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    return d->size_isValid;
}

QList<OAIAggregationOption> OAISearchRequest::getAggregations() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return {};
    }
    return d->aggregations;
}
void OAISearchRequest::setAggregations(const QList<OAIAggregationOption> &aggregations) {
    Q_D(OAISearchRequest);
    Q_ASSERT(d);

    d->aggregations = aggregations;
    d->aggregations_isSet = true;
}

bool OAISearchRequest::is_aggregations_Set() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }

    return d->aggregations_isSet;
}

bool OAISearchRequest::is_aggregations_Valid() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    return d->aggregations_isValid;
}

QList<QString> OAISearchRequest::getAggregationFilters() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return {};
    }
    return d->aggregation_filters;
}
void OAISearchRequest::setAggregationFilters(const QList<QString> &aggregation_filters) {
    Q_D(OAISearchRequest);
    Q_ASSERT(d);

    d->aggregation_filters = aggregation_filters;
    d->aggregation_filters_isSet = true;
}

bool OAISearchRequest::is_aggregation_filters_Set() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }

    return d->aggregation_filters_isSet;
}

bool OAISearchRequest::is_aggregation_filters_Valid() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    return d->aggregation_filters_isValid;
}

QList<OAISortProperty> OAISearchRequest::getSortProperties() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return {};
    }
    return d->sort_properties;
}
void OAISearchRequest::setSortProperties(const QList<OAISortProperty> &sort_properties) {
    Q_D(OAISearchRequest);
    Q_ASSERT(d);

    d->sort_properties = sort_properties;
    d->sort_properties_isSet = true;
}

bool OAISearchRequest::is_sort_properties_Set() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }

    return d->sort_properties_isSet;
}

bool OAISearchRequest::is_sort_properties_Valid() const{
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    return d->sort_properties_isValid;
}

bool OAISearchRequest::isSet() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->entity_types.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->query.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (d->from_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->size_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->aggregations.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->aggregation_filters.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (d->sort_properties.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchRequest::isValid() const {
    Q_D(const OAISearchRequest);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->entity_types_isValid && d->query_isValid && true;
}

} // namespace OpenAPI
