// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchRequest.h
 *
 * Represents an individual search request within a search query. Follows the [MS Graph searchRequest](https://learn.microsoft.com/en-us/graph/api/resources/searchrequest) resource type. 
 */

#ifndef OAISearchRequest_H
#define OAISearchRequest_H

#include <QJsonObject>

#include "OAIAggregationOption.h"
#include "OAISearchQuery.h"
#include "OAISortProperty.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAISearchQuery;
class OAIAggregationOption;
class OAISortProperty;


class OAISearchRequestPrivate;

class OAISearchRequest : public OAIObject {
public:
    OAISearchRequest();
    OAISearchRequest(const OAISearchRequest &other);
    OAISearchRequest(QString json);
    ~OAISearchRequest() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<QString> getEntityTypes() const;
    void setEntityTypes(const QList<QString> &entity_types);
    bool is_entity_types_Set() const;
    bool is_entity_types_Valid() const;

    OAISearchQuery getQuery() const;
    void setQuery(const OAISearchQuery &query);
    bool is_query_Set() const;
    bool is_query_Valid() const;

    qint32 getFrom() const;
    void setFrom(const qint32 &from);
    bool is_from_Set() const;
    bool is_from_Valid() const;

    qint32 getSize() const;
    void setSize(const qint32 &size);
    bool is_size_Set() const;
    bool is_size_Valid() const;

    QList<OAIAggregationOption> getAggregations() const;
    void setAggregations(const QList<OAIAggregationOption> &aggregations);
    bool is_aggregations_Set() const;
    bool is_aggregations_Valid() const;

    QList<QString> getAggregationFilters() const;
    void setAggregationFilters(const QList<QString> &aggregation_filters);
    bool is_aggregation_filters_Set() const;
    bool is_aggregation_filters_Valid() const;

    QList<OAISortProperty> getSortProperties() const;
    void setSortProperties(const QList<OAISortProperty> &sort_properties);
    bool is_sort_properties_Set() const;
    bool is_sort_properties_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchRequest)
    QSharedPointer<OAISearchRequestPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchRequest)

#endif // OAISearchRequest_H
