// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchHit.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchHitPrivate {
    friend class OAISearchHit;

     QString hit_id;
     bool hit_id_isSet;
     bool hit_id_isValid;

     qint32 rank;
     bool rank_isSet;
     bool rank_isValid;

     QString summary;
     bool summary_isSet;
     bool summary_isValid;

     OAIDriveItem resource;
     bool resource_isSet;
     bool resource_isValid;
};

OAISearchHit::OAISearchHit()
    : d_ptr()
{
}

OAISearchHit::OAISearchHit(const OAISearchHit& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchHit::OAISearchHit(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchHit::~OAISearchHit() = default;

void OAISearchHit::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchHitPrivate{});

        Q_D(OAISearchHit);


        d->hit_id_isSet = false;
        d->hit_id_isValid = false;

        d->rank_isSet = false;
        d->rank_isValid = false;

        d->summary_isSet = false;
        d->summary_isValid = false;

        d->resource_isSet = false;
        d->resource_isValid = false;
    }
}

void OAISearchHit::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchHit::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchHit);

    d->hit_id_isValid = ::OpenAPI::fromJsonValue(d->hit_id, json[QString("hitId")]);
    d->hit_id_isSet = !json[QString("hitId")].isNull() && d->hit_id_isValid;

    d->rank_isValid = ::OpenAPI::fromJsonValue(d->rank, json[QString("rank")]);
    d->rank_isSet = !json[QString("rank")].isNull() && d->rank_isValid;

    d->summary_isValid = ::OpenAPI::fromJsonValue(d->summary, json[QString("summary")]);
    d->summary_isSet = !json[QString("summary")].isNull() && d->summary_isValid;

    d->resource_isValid = ::OpenAPI::fromJsonValue(d->resource, json[QString("resource")]);
    d->resource_isSet = !json[QString("resource")].isNull() && d->resource_isValid;
}

QString OAISearchHit::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchHit::asJsonObject() const {
    Q_D(const OAISearchHit);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->hit_id_isSet) {
        obj.insert(QString("hitId"), ::OpenAPI::toJsonValue(d->hit_id));
    }
    if (d->rank_isSet) {
        obj.insert(QString("rank"), ::OpenAPI::toJsonValue(d->rank));
    }
    if (d->summary_isSet) {
        obj.insert(QString("summary"), ::OpenAPI::toJsonValue(d->summary));
    }
    if (d->resource.isSet()) {
        obj.insert(QString("resource"), ::OpenAPI::toJsonValue(d->resource));
    }
    return obj;
}

QString OAISearchHit::getHitId() const {
    Q_D(const OAISearchHit);
    if(!d){
        return {};
    }
    return d->hit_id;
}
void OAISearchHit::setHitId(const QString &hit_id) {
    Q_D(OAISearchHit);
    Q_ASSERT(d);

    d->hit_id = hit_id;
    d->hit_id_isSet = true;
}

bool OAISearchHit::is_hit_id_Set() const{
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }

    return d->hit_id_isSet;
}

bool OAISearchHit::is_hit_id_Valid() const{
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }
    return d->hit_id_isValid;
}

qint32 OAISearchHit::getRank() const {
    Q_D(const OAISearchHit);
    if(!d){
        return {};
    }
    return d->rank;
}
void OAISearchHit::setRank(const qint32 &rank) {
    Q_D(OAISearchHit);
    Q_ASSERT(d);

    d->rank = rank;
    d->rank_isSet = true;
}

bool OAISearchHit::is_rank_Set() const{
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }

    return d->rank_isSet;
}

bool OAISearchHit::is_rank_Valid() const{
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }
    return d->rank_isValid;
}

QString OAISearchHit::getSummary() const {
    Q_D(const OAISearchHit);
    if(!d){
        return {};
    }
    return d->summary;
}
void OAISearchHit::setSummary(const QString &summary) {
    Q_D(OAISearchHit);
    Q_ASSERT(d);

    d->summary = summary;
    d->summary_isSet = true;
}

bool OAISearchHit::is_summary_Set() const{
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }

    return d->summary_isSet;
}

bool OAISearchHit::is_summary_Valid() const{
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }
    return d->summary_isValid;
}

OAIDriveItem OAISearchHit::getResource() const {
    Q_D(const OAISearchHit);
    if(!d){
        return {};
    }
    return d->resource;
}
void OAISearchHit::setResource(const OAIDriveItem &resource) {
    Q_D(OAISearchHit);
    Q_ASSERT(d);

    d->resource = resource;
    d->resource_isSet = true;
}

bool OAISearchHit::is_resource_Set() const{
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }

    return d->resource_isSet;
}

bool OAISearchHit::is_resource_Valid() const{
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }
    return d->resource_isValid;
}

bool OAISearchHit::isSet() const {
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->hit_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->rank_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->summary_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->resource.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchHit::isValid() const {
    Q_D(const OAISearchHit);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
