// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchQuery_request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchQuery_requestPrivate {
    friend class OAISearchQuery_request;

     QList<OAISearchRequest> requests;
     bool requests_isSet;
     bool requests_isValid;
};

OAISearchQuery_request::OAISearchQuery_request()
    : d_ptr()
{
}

OAISearchQuery_request::OAISearchQuery_request(const OAISearchQuery_request& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchQuery_request::OAISearchQuery_request(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchQuery_request::~OAISearchQuery_request() = default;

void OAISearchQuery_request::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchQuery_requestPrivate{});

        Q_D(OAISearchQuery_request);


        d->requests_isSet = false;
        d->requests_isValid = false;
    }
}

void OAISearchQuery_request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchQuery_request::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchQuery_request);

    d->requests_isValid = ::OpenAPI::fromJsonValue(d->requests, json[QString("requests")]);
    d->requests_isSet = !json[QString("requests")].isNull() && d->requests_isValid;
}

QString OAISearchQuery_request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchQuery_request::asJsonObject() const {
    Q_D(const OAISearchQuery_request);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->requests.size() > 0) {
        obj.insert(QString("requests"), ::OpenAPI::toJsonValue(d->requests));
    }
    return obj;
}

QList<OAISearchRequest> OAISearchQuery_request::getRequests() const {
    Q_D(const OAISearchQuery_request);
    if(!d){
        return {};
    }
    return d->requests;
}
void OAISearchQuery_request::setRequests(const QList<OAISearchRequest> &requests) {
    Q_D(OAISearchQuery_request);
    Q_ASSERT(d);

    d->requests = requests;
    d->requests_isSet = true;
}

bool OAISearchQuery_request::is_requests_Set() const{
    Q_D(const OAISearchQuery_request);
    if(!d){
        return false;
    }

    return d->requests_isSet;
}

bool OAISearchQuery_request::is_requests_Valid() const{
    Q_D(const OAISearchQuery_request);
    if(!d){
        return false;
    }
    return d->requests_isValid;
}

bool OAISearchQuery_request::isSet() const {
    Q_D(const OAISearchQuery_request);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->requests.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchQuery_request::isValid() const {
    Q_D(const OAISearchQuery_request);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->requests_isValid && true;
}

} // namespace OpenAPI
