// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchQuery_200_response.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchQuery_200_responsePrivate {
    friend class OAISearchQuery_200_response;

     QList<OAISearchResponse> value;
     bool value_isSet;
     bool value_isValid;
};

OAISearchQuery_200_response::OAISearchQuery_200_response()
    : d_ptr()
{
}

OAISearchQuery_200_response::OAISearchQuery_200_response(const OAISearchQuery_200_response& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchQuery_200_response::OAISearchQuery_200_response(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchQuery_200_response::~OAISearchQuery_200_response() = default;

void OAISearchQuery_200_response::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchQuery_200_responsePrivate{});

        Q_D(OAISearchQuery_200_response);


        d->value_isSet = false;
        d->value_isValid = false;
    }
}

void OAISearchQuery_200_response::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchQuery_200_response::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchQuery_200_response);

    d->value_isValid = ::OpenAPI::fromJsonValue(d->value, json[QString("value")]);
    d->value_isSet = !json[QString("value")].isNull() && d->value_isValid;
}

QString OAISearchQuery_200_response::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchQuery_200_response::asJsonObject() const {
    Q_D(const OAISearchQuery_200_response);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->value.size() > 0) {
        obj.insert(QString("value"), ::OpenAPI::toJsonValue(d->value));
    }
    return obj;
}

QList<OAISearchResponse> OAISearchQuery_200_response::getValue() const {
    Q_D(const OAISearchQuery_200_response);
    if(!d){
        return {};
    }
    return d->value;
}
void OAISearchQuery_200_response::setValue(const QList<OAISearchResponse> &value) {
    Q_D(OAISearchQuery_200_response);
    Q_ASSERT(d);

    d->value = value;
    d->value_isSet = true;
}

bool OAISearchQuery_200_response::is_value_Set() const{
    Q_D(const OAISearchQuery_200_response);
    if(!d){
        return false;
    }

    return d->value_isSet;
}

bool OAISearchQuery_200_response::is_value_Valid() const{
    Q_D(const OAISearchQuery_200_response);
    if(!d){
        return false;
    }
    return d->value_isValid;
}

bool OAISearchQuery_200_response::isSet() const {
    Q_D(const OAISearchQuery_200_response);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->value.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchQuery_200_response::isValid() const {
    Q_D(const OAISearchQuery_200_response);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
