// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearchBucket.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISearchBucketPrivate {
    friend class OAISearchBucket;

     QString key;
     bool key_isSet;
     bool key_isValid;

     qint64 count;
     bool count_isSet;
     bool count_isValid;

     QString aggregation_filter_token;
     bool aggregation_filter_token_isSet;
     bool aggregation_filter_token_isValid;

     QList<OAISearchAggregation> libre_graph_sub_aggregations;
     bool libre_graph_sub_aggregations_isSet;
     bool libre_graph_sub_aggregations_isValid;
};

OAISearchBucket::OAISearchBucket()
    : d_ptr()
{
}

OAISearchBucket::OAISearchBucket(const OAISearchBucket& other)
    : d_ptr(other.d_ptr)
{
}

OAISearchBucket::OAISearchBucket(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISearchBucket::~OAISearchBucket() = default;

void OAISearchBucket::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISearchBucketPrivate{});

        Q_D(OAISearchBucket);


        d->key_isSet = false;
        d->key_isValid = false;

        d->count_isSet = false;
        d->count_isValid = false;

        d->aggregation_filter_token_isSet = false;
        d->aggregation_filter_token_isValid = false;

        d->libre_graph_sub_aggregations_isSet = false;
        d->libre_graph_sub_aggregations_isValid = false;
    }
}

void OAISearchBucket::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearchBucket::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISearchBucket);

    d->key_isValid = ::OpenAPI::fromJsonValue(d->key, json[QString("key")]);
    d->key_isSet = !json[QString("key")].isNull() && d->key_isValid;

    d->count_isValid = ::OpenAPI::fromJsonValue(d->count, json[QString("count")]);
    d->count_isSet = !json[QString("count")].isNull() && d->count_isValid;

    d->aggregation_filter_token_isValid = ::OpenAPI::fromJsonValue(d->aggregation_filter_token, json[QString("aggregationFilterToken")]);
    d->aggregation_filter_token_isSet = !json[QString("aggregationFilterToken")].isNull() && d->aggregation_filter_token_isValid;

    d->libre_graph_sub_aggregations_isValid = ::OpenAPI::fromJsonValue(d->libre_graph_sub_aggregations, json[QString("@libre.graph.subAggregations")]);
    d->libre_graph_sub_aggregations_isSet = !json[QString("@libre.graph.subAggregations")].isNull() && d->libre_graph_sub_aggregations_isValid;
}

QString OAISearchBucket::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearchBucket::asJsonObject() const {
    Q_D(const OAISearchBucket);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->key_isSet) {
        obj.insert(QString("key"), ::OpenAPI::toJsonValue(d->key));
    }
    if (d->count_isSet) {
        obj.insert(QString("count"), ::OpenAPI::toJsonValue(d->count));
    }
    if (d->aggregation_filter_token_isSet) {
        obj.insert(QString("aggregationFilterToken"), ::OpenAPI::toJsonValue(d->aggregation_filter_token));
    }
    if (d->libre_graph_sub_aggregations.size() > 0) {
        obj.insert(QString("@libre.graph.subAggregations"), ::OpenAPI::toJsonValue(d->libre_graph_sub_aggregations));
    }
    return obj;
}

QString OAISearchBucket::getKey() const {
    Q_D(const OAISearchBucket);
    if(!d){
        return {};
    }
    return d->key;
}
void OAISearchBucket::setKey(const QString &key) {
    Q_D(OAISearchBucket);
    Q_ASSERT(d);

    d->key = key;
    d->key_isSet = true;
}

bool OAISearchBucket::is_key_Set() const{
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }

    return d->key_isSet;
}

bool OAISearchBucket::is_key_Valid() const{
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }
    return d->key_isValid;
}

qint64 OAISearchBucket::getCount() const {
    Q_D(const OAISearchBucket);
    if(!d){
        return {};
    }
    return d->count;
}
void OAISearchBucket::setCount(const qint64 &count) {
    Q_D(OAISearchBucket);
    Q_ASSERT(d);

    d->count = count;
    d->count_isSet = true;
}

bool OAISearchBucket::is_count_Set() const{
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }

    return d->count_isSet;
}

bool OAISearchBucket::is_count_Valid() const{
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }
    return d->count_isValid;
}

QString OAISearchBucket::getAggregationFilterToken() const {
    Q_D(const OAISearchBucket);
    if(!d){
        return {};
    }
    return d->aggregation_filter_token;
}
void OAISearchBucket::setAggregationFilterToken(const QString &aggregation_filter_token) {
    Q_D(OAISearchBucket);
    Q_ASSERT(d);

    d->aggregation_filter_token = aggregation_filter_token;
    d->aggregation_filter_token_isSet = true;
}

bool OAISearchBucket::is_aggregation_filter_token_Set() const{
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }

    return d->aggregation_filter_token_isSet;
}

bool OAISearchBucket::is_aggregation_filter_token_Valid() const{
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }
    return d->aggregation_filter_token_isValid;
}

QList<OAISearchAggregation> OAISearchBucket::getLibreGraphSubAggregations() const {
    Q_D(const OAISearchBucket);
    if(!d){
        return {};
    }
    return d->libre_graph_sub_aggregations;
}
void OAISearchBucket::setLibreGraphSubAggregations(const QList<OAISearchAggregation> &libre_graph_sub_aggregations) {
    Q_D(OAISearchBucket);
    Q_ASSERT(d);

    d->libre_graph_sub_aggregations = libre_graph_sub_aggregations;
    d->libre_graph_sub_aggregations_isSet = true;
}

bool OAISearchBucket::is_libre_graph_sub_aggregations_Set() const{
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }

    return d->libre_graph_sub_aggregations_isSet;
}

bool OAISearchBucket::is_libre_graph_sub_aggregations_Valid() const{
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }
    return d->libre_graph_sub_aggregations_isValid;
}

bool OAISearchBucket::isSet() const {
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->count_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->aggregation_filter_token_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->libre_graph_sub_aggregations.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearchBucket::isValid() const {
    Q_D(const OAISearchBucket);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
