// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchQuery.h
 *
 * Represents the search query. Follows the [MS Graph searchQuery](https://learn.microsoft.com/en-us/graph/api/resources/searchquery) resource type. 
 */

#ifndef OAISearchQuery_H
#define OAISearchQuery_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {


class OAISearchQueryPrivate;

class OAISearchQuery : public OAIObject {
public:
    OAISearchQuery();
    OAISearchQuery(const OAISearchQuery &other);
    OAISearchQuery(QString json);
    ~OAISearchQuery() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getQueryString() const;
    void setQueryString(const QString &query_string);
    bool is_query_string_Set() const;
    bool is_query_string_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchQuery)
    QSharedPointer<OAISearchQueryPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchQuery)

#endif // OAISearchQuery_H
