// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISortProperty.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAISortPropertyPrivate {
    friend class OAISortProperty;

     QString name;
     bool name_isSet;
     bool name_isValid;

     bool is_descending;
     bool is_descending_isSet;
     bool is_descending_isValid;
};

OAISortProperty::OAISortProperty()
    : d_ptr()
{
}

OAISortProperty::OAISortProperty(const OAISortProperty& other)
    : d_ptr(other.d_ptr)
{
}

OAISortProperty::OAISortProperty(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAISortProperty::~OAISortProperty() = default;

void OAISortProperty::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAISortPropertyPrivate{});

        Q_D(OAISortProperty);


        d->name_isSet = false;
        d->name_isValid = false;

        d->is_descending_isSet = false;
        d->is_descending_isValid = false;
    }
}

void OAISortProperty::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISortProperty::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAISortProperty);

    d->name_isValid = ::OpenAPI::fromJsonValue(d->name, json[QString("name")]);
    d->name_isSet = !json[QString("name")].isNull() && d->name_isValid;

    d->is_descending_isValid = ::OpenAPI::fromJsonValue(d->is_descending, json[QString("isDescending")]);
    d->is_descending_isSet = !json[QString("isDescending")].isNull() && d->is_descending_isValid;
}

QString OAISortProperty::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISortProperty::asJsonObject() const {
    Q_D(const OAISortProperty);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(d->name));
    }
    if (d->is_descending_isSet) {
        obj.insert(QString("isDescending"), ::OpenAPI::toJsonValue(d->is_descending));
    }
    return obj;
}

QString OAISortProperty::getName() const {
    Q_D(const OAISortProperty);
    if(!d){
        return {};
    }
    return d->name;
}
void OAISortProperty::setName(const QString &name) {
    Q_D(OAISortProperty);
    Q_ASSERT(d);

    d->name = name;
    d->name_isSet = true;
}

bool OAISortProperty::is_name_Set() const{
    Q_D(const OAISortProperty);
    if(!d){
        return false;
    }

    return d->name_isSet;
}

bool OAISortProperty::is_name_Valid() const{
    Q_D(const OAISortProperty);
    if(!d){
        return false;
    }
    return d->name_isValid;
}

bool OAISortProperty::isIsDescending() const {
    Q_D(const OAISortProperty);
    if(!d){
        return {};
    }
    return d->is_descending;
}
void OAISortProperty::setIsDescending(const bool &is_descending) {
    Q_D(OAISortProperty);
    Q_ASSERT(d);

    d->is_descending = is_descending;
    d->is_descending_isSet = true;
}

bool OAISortProperty::is_is_descending_Set() const{
    Q_D(const OAISortProperty);
    if(!d){
        return false;
    }

    return d->is_descending_isSet;
}

bool OAISortProperty::is_is_descending_Valid() const{
    Q_D(const OAISortProperty);
    if(!d){
        return false;
    }
    return d->is_descending_isValid;
}

bool OAISortProperty::isSet() const {
    Q_D(const OAISortProperty);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->is_descending_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISortProperty::isValid() const {
    Q_D(const OAISortProperty);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return d->name_isValid && true;
}

} // namespace OpenAPI
