// model-header.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.8
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAISearchHit.h
 *
 * Represents an individual search result. Follows the [MS Graph searchHit](https://learn.microsoft.com/en-us/graph/api/resources/searchhit) resource type. 
 */

#ifndef OAISearchHit_H
#define OAISearchHit_H

#include <QJsonObject>

#include "OAIDriveItem.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIDriveItem;


class OAISearchHitPrivate;

class OAISearchHit : public OAIObject {
public:
    OAISearchHit();
    OAISearchHit(const OAISearchHit &other);
    OAISearchHit(QString json);
    ~OAISearchHit() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getHitId() const;
    void setHitId(const QString &hit_id);
    bool is_hit_id_Set() const;
    bool is_hit_id_Valid() const;

    qint32 getRank() const;
    void setRank(const qint32 &rank);
    bool is_rank_Set() const;
    bool is_rank_Valid() const;

    QString getSummary() const;
    void setSummary(const QString &summary);
    bool is_summary_Set() const;
    bool is_summary_Valid() const;

    OAIDriveItem getResource() const;
    void setResource(const OAIDriveItem &resource);
    bool is_resource_Set() const;
    bool is_resource_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();
    Q_DECLARE_PRIVATE(OAISearchHit)
    QSharedPointer<OAISearchHitPrivate> d_ptr;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAISearchHit)

#endif // OAISearchHit_H
